// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetrylocks.sql

package database

import (
	"context"
	"time"
)

const deleteOldTelemetryLocks = `-- name: DeleteOldTelemetryLocks :exec
DELETE FROM
    telemetry_locks
WHERE
    period_ending_at < $1::timestamptz
`

// Deletes old telemetry locks from the telemetry_locks table.
func (q *Queries) DeleteOldTelemetryLocks(ctx context.Context, periodEndingAtBefore time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldTelemetryLocks, periodEndingAtBefore)
	return err
}

const insertTelemetryLock = `-- name: InsertTelemetryLock :exec
INSERT INTO
    telemetry_locks (event_type, period_ending_at)
VALUES
    ($1, $2)
`

type InsertTelemetryLockParams struct {
	EventType      string    `db:"event_type" json:"event_type"`
	PeriodEndingAt time.Time `db:"period_ending_at" json:"period_ending_at"`
}

// Inserts a new lock row into the telemetry_locks table. Replicas should call
// this function prior to attempting to generate or publish a heartbeat event to
// the telemetry service.
// If the query returns a duplicate primary key error, the replica should not
// attempt to generate or publish the event to the telemetry service.
func (q *Queries) InsertTelemetryLock(ctx context.Context, arg InsertTelemetryLockParams) error {
	_, err := q.db.ExecContext(ctx, insertTelemetryLock, arg.EventType, arg.PeriodEndingAt)
	return err
}
