package chattool

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"slices"
	"strings"

	"charm.land/fantasy"

	"github.com/coder/coder/v2/codersdk"
	"github.com/coder/coder/v2/codersdk/workspacesdk"
)

type EditFilesOptions struct {
	GetWorkspaceConn func(context.Context) (workspacesdk.AgentConn, error)
	ResolvePlanPath  func(context.Context) (chatPath string, home string, err error)
	IsPlanTurn       bool
}

// EditFilesArgs is the tool input schema, auto-generated by the
// fantasy framework from these struct tags.
type EditFilesArgs struct {
	Edits []EditFilesEdit `json:"edits"`
}

// EditFilesEdit is one edit in the flat edit_files input: a single
// old_text to new_text replacement that carries the path of the file
// it applies to. It is distinct from workspacesdk.FileEdit, which has
// no path and is grouped under workspacesdk.FileEdits for the agent.
type EditFilesEdit struct {
	Path       string `json:"path" description:"Absolute path of the file to edit."`
	OldText    string `json:"old_text" description:"Exact text to replace. Must match exactly one location unless replace_all is true. Must differ from new_text."`
	NewText    string `json:"new_text" description:"Replacement text."`
	ReplaceAll bool   `json:"replace_all,omitempty" description:"Replace every match of old_text."`
}

// GroupEditsByPath groups edits into one entry per path for the
// workspace agent request. Paths compare exactly as given. Files
// appear in order of each path's first edit, and each file keeps its
// edits in their original order, so interleaved paths (a, b, a) group
// to a: [1st, 3rd], b: [2nd]. The result is empty, not nil, for empty
// input.
func GroupEditsByPath(edits []EditFilesEdit) []workspacesdk.FileEdits {
	files := make([]workspacesdk.FileEdits, 0, len(edits))
	indexByPath := make(map[string]int, len(edits))
	for _, edit := range edits {
		i, ok := indexByPath[edit.Path]
		if !ok {
			i = len(files)
			indexByPath[edit.Path] = i
			files = append(files, workspacesdk.FileEdits{Path: edit.Path})
		}
		files[i].Edits = append(files[i].Edits, workspacesdk.FileEdit{
			OldText:    edit.OldText,
			NewText:    edit.NewText,
			ReplaceAll: edit.ReplaceAll,
		})
	}
	return files
}

// EditFilesHookInput is the grouped form of edit_files input that
// pre_tool_use hooks receive as tool_input and return as
// input_override: {"files":[{"path":...,"edits":[...]}]}.
//
// It deliberately does not reuse workspacesdk.FileEdits: the JSON
// methods on workspacesdk.FileEdit emit and accept the deprecated
// search/replace keys for old agents, and hooks must see and send only
// old_text/new_text.
type EditFilesHookInput struct {
	Files []EditFilesHookFile `json:"files"`
}

// EditFilesHookFile holds the edits for one path in
// EditFilesHookInput.
type EditFilesHookFile struct {
	Path  string              `json:"path"`
	Edits []EditFilesHookEdit `json:"edits"`
}

// EditFilesHookEdit is one edit in EditFilesHookFile.
type EditFilesHookEdit struct {
	OldText    string `json:"old_text"`
	NewText    string `json:"new_text"`
	ReplaceAll bool   `json:"replace_all,omitempty"`
}

// NewEditFilesHookInput groups edits by path with the same ordering
// as GroupEditsByPath.
func NewEditFilesHookInput(edits []EditFilesEdit) EditFilesHookInput {
	grouped := GroupEditsByPath(edits)
	input := EditFilesHookInput{Files: make([]EditFilesHookFile, 0, len(grouped))}
	for _, file := range grouped {
		hookFile := EditFilesHookFile{
			Path:  file.Path,
			Edits: make([]EditFilesHookEdit, 0, len(file.Edits)),
		}
		for _, edit := range file.Edits {
			hookFile.Edits = append(hookFile.Edits, EditFilesHookEdit(edit))
		}
		input.Files = append(input.Files, hookFile)
	}
	return input
}

// Edits flattens the grouped input back to one edit per entry: files
// in order, then each file's edits in order. The result is empty, not
// nil, when there are no edits.
func (in EditFilesHookInput) Edits() []EditFilesEdit {
	edits := make([]EditFilesEdit, 0)
	for _, file := range in.Files {
		for _, edit := range file.Edits {
			edits = append(edits, EditFilesEdit{
				Path:       file.Path,
				OldText:    edit.OldText,
				NewText:    edit.NewText,
				ReplaceAll: edit.ReplaceAll,
			})
		}
	}
	return edits
}

// EditFilesName is the name of the edit_files tool.
const EditFilesName = "edit_files"

// NormalizeEditPaths returns a copy of edits with each path in the form
// the tool executes it: surrounding whitespace removed. The hook
// presentation uses the same function so hooks see the paths the tool
// edits.
func NormalizeEditPaths(edits []EditFilesEdit) []EditFilesEdit {
	normalized := slices.Clone(edits)
	for i := range normalized {
		normalized[i].Path = strings.TrimSpace(normalized[i].Path)
	}
	return normalized
}

// editFilesExample is the input example shown when the model sends a
// shape the tool does not accept.
const editFilesExample = `{"edits":[{"path":"/repo/a.go","old_text":"x := 1","new_text":"x := 2"},{"path":"/repo/b.go","old_text":"foo()","new_text":"bar()"}]}`

// editFilesTool adds input handling that the typed fantasy wrapper
// cannot express: decoding a string-encoded edits array where the call
// arrives, and whole-call errors that show the accepted shape.
type editFilesTool struct {
	fantasy.AgentTool
}

// DecodeToolInput replaces a top-level edits value that is a JSON
// string with the string's content when that content parses as-is into
// a JSON array of objects. The content bytes are spliced in verbatim
// and the rest of the input is kept byte for byte, so the ambiguity
// check still sees the model's key spelling. Any other input, including
// a repeated or differently capitalized edits key, returns false and is
// left for the ambiguity check and the tool to reject.
func (editFilesTool) DecodeToolInput(input string) (string, bool) {
	decoder := json.NewDecoder(strings.NewReader(input))
	if token, err := decoder.Token(); err != nil || token != json.Delim('{') {
		return "", false
	}
	var (
		content    string
		start, end = -1, -1
	)
	for decoder.More() {
		token, err := decoder.Token()
		if err != nil {
			return "", false
		}
		key, _ := token.(string)
		var value json.RawMessage
		if err := decoder.Decode(&value); err != nil {
			return "", false
		}
		if key != "edits" {
			continue
		}
		if start >= 0 {
			return "", false
		}
		if err := json.Unmarshal(value, &content); err != nil {
			return "", false
		}
		end = int(decoder.InputOffset())
		start = end - len(value)
	}
	if token, err := decoder.Token(); err != nil || token != json.Delim('}') {
		return "", false
	}
	if _, err := decoder.Token(); !errors.Is(err, io.EOF) {
		return "", false
	}
	if start < 0 || !isJSONArrayOfObjects(content) {
		return "", false
	}
	return input[:start] + content + input[end:], true
}

// isJSONArrayOfObjects reports whether text is exactly one JSON array
// whose elements are all objects. json.Unmarshal accepts only JSON
// whitespace around the value, so text that passes can be spliced into
// the input unchanged.
func isJSONArrayOfObjects(text string) bool {
	var items []json.RawMessage
	if err := json.Unmarshal([]byte(text), &items); err != nil || items == nil {
		return false
	}
	for _, item := range items {
		if !strings.HasPrefix(strings.TrimLeft(string(item), " \t\r\n"), "{") {
			return false
		}
	}
	return true
}

// Run rejects the retired files shape and input that does not decode
// into EditFilesArgs. Both messages start with what to change and show
// the accepted shape; the decode message also carries the decode error.
func (t editFilesTool) Run(ctx context.Context, call fantasy.ToolCall) (fantasy.ToolResponse, error) {
	var retired struct {
		Files json.RawMessage `json:"files"`
	}
	if err := json.Unmarshal([]byte(call.Input), &retired); err == nil && retired.Files != nil {
		return rejectEditFiles(
			"Send a flat edits list where every edit has its own path, for example " + editFilesExample +
				"; the files key is not supported",
		), nil
	}
	var args EditFilesArgs
	if err := json.Unmarshal([]byte(call.Input), &args); err != nil {
		return rejectEditFiles(fmt.Sprintf(
			"Send edits as a JSON array of objects with string path, old_text and new_text and optional boolean replace_all, for example %s; the input did not match (%s)",
			editFilesExample, err,
		)), nil
	}
	return t.AgentTool.Run(ctx, call)
}

func EditFiles(options EditFilesOptions) fantasy.AgentTool {
	return editFilesTool{AgentTool: fantasy.NewAgentTool(
		EditFilesName,
		"Perform edits on one or more files by replacing old_text with"+
			" new_text. Send a flat list of edits; each edit carries the"+
			" absolute path of the file it changes, and edits to the same"+
			" file apply in the order listed. Matching is fuzzy"+
			" (tolerates whitespace and indentation differences) and preserves"+
			" the file's existing indentation and line endings. Errors if"+
			" old_text matches zero locations, or more than one unless"+
			" replace_all is set. Each file's edits are validated before that"+
			" file is written: a file with any error is left unchanged, and"+
			" the other files are still applied.",
		func(ctx context.Context, args EditFilesArgs, _ fantasy.ToolCall) (fantasy.ToolResponse, error) {
			if len(args.Edits) == 0 {
				return rejectEditFiles("Add at least one edit to edits"), nil
			}
			var missingPath []string
			args.Edits = NormalizeEditPaths(args.Edits)
			for i, edit := range args.Edits {
				if edit.Path == "" {
					missingPath = append(missingPath, fmt.Sprintf("edits[%d]", i))
				}
			}
			if len(missingPath) > 0 {
				return rejectEditFiles(
					"Set path to the absolute path of the file to edit in " + strings.Join(missingPath, ", ") +
						"; path is required in every edit",
				), nil
			}
			var planPath string
			if options.IsPlanTurn {
				resolvedPlanPath, err := resolvePlanTurnPath(ctx, options.ResolvePlanPath)
				if err != nil {
					return rejectEditFiles(err.Error()), nil
				}
				for _, edit := range args.Edits {
					if edit.Path != resolvedPlanPath {
						return rejectEditFiles("Edit only " + resolvedPlanPath + "; during plan turns, edit_files is restricted to that file"), nil
					}
				}
				planPath = resolvedPlanPath
			}
			if options.GetWorkspaceConn == nil {
				return rejectEditFiles("workspace connection resolver is not configured"), nil
			}
			conn, err := options.GetWorkspaceConn(ctx)
			if err != nil {
				return rejectEditFiles(err.Error()), nil
			}
			if planPath != "" {
				if err := ensurePlanPathResolvesToItself(ctx, conn, planPath); err != nil {
					return rejectEditFiles(err.Error()), nil
				}
			}
			return executeEditFilesTool(ctx, conn, args, options.ResolvePlanPath)
		},
	)}
}

// executeEditFilesTool applies each file in its own agent request, in
// order of each path's first edit, so a file with an error does not
// stop the others. Results index edits by their position in args.
func executeEditFilesTool(
	ctx context.Context,
	conn workspacesdk.AgentConn,
	args EditFilesArgs,
	resolvePlanPath func(context.Context) (chatPath string, home string, err error),
) (fantasy.ToolResponse, error) {
	editIndexes := make(map[string][]int)
	for i, edit := range args.Edits {
		editIndexes[edit.Path] = append(editIndexes[edit.Path], i)
	}

	var (
		chatPath       string
		home           string
		planPathErr    error
		planPathLoaded bool
	)
	// checkFile runs the coderd checks tied to one file and returns the
	// reason to reject that file, or "" when it passes.
	checkFile := func(path string, indexes []int) string {
		hasPlanFileName := looksLikePlanFileName(path)
		if hasPlanFileName && !isAbsolutePath(path) {
			return "Use the chat-specific absolute plan path; plan files must use absolute paths"
		}
		if resolvePlanPath != nil && hasPlanFileName {
			if !planPathLoaded {
				chatPath, home, planPathErr = resolvePlanPath(ctx)
				planPathLoaded = true
			}
			if resp, rejected := rejectSharedPlanPath(path, home, chatPath, planPathErr); rejected {
				return resp.Content
			}
		}
		// A no-op edit rejects its whole file like any other error in the
		// file: calls with one are followed by rework on that file more
		// often than other calls, so its other edits wait for the resend.
		// The comparison is exact because texts that differ only in
		// whitespace or line endings can still change the file.
		var noOps []int
		for _, i := range indexes {
			if args.Edits[i].OldText == args.Edits[i].NewText {
				noOps = append(noOps, i)
			}
		}
		switch len(noOps) {
		case 0:
			return ""
		case 1:
			return "Change new_text or remove the edit: " + formatEditIndexes(noOps) + " has identical old_text and new_text, so it changes nothing"
		default:
			return "Change new_text or remove the edits: " + formatEditIndexes(noOps) + " have identical old_text and new_text, so they change nothing"
		}
	}

	var applied, notApplied []editFilesFileResult
	for _, file := range GroupEditsByPath(args.Edits) {
		indexes := editIndexes[file.Path]
		// The interrupt handler can persist a result produced after
		// cancellation, so a file not yet sent is reported as not
		// applied instead of failing with an outcome that looks unknown.
		// This runs first so the interrupt, not a check that needs the
		// workspace, is the reason given.
		if ctx.Err() != nil {
			notApplied = append(notApplied, editFilesFileResult{
				Path: file.Path, Status: editFilesStatusRejected, Edits: indexes, Error: editFilesInterruptedError,
			})
			continue
		}
		if reason := checkFile(file.Path, indexes); reason != "" {
			notApplied = append(notApplied, editFilesFileResult{
				Path: file.Path, Status: editFilesStatusRejected, Edits: indexes, Error: reason,
			})
			continue
		}
		resp, err := conn.EditFiles(ctx, workspacesdk.FileEditRequest{
			Files:       []workspacesdk.FileEdits{file},
			IncludeDiff: true,
		})
		if err != nil {
			status := editFilesStatusUnknown
			if isAgentResponse(err) {
				status = editFilesStatusRejected
			}
			notApplied = append(notApplied, editFilesFileResult{
				Path: file.Path, Status: status, Edits: indexes, Error: agentAPIErrorMessage(err),
			})
			continue
		}
		result := editFilesFileResult{Path: file.Path, Status: editFilesStatusApplied}
		// Agents that predate per-file results return none.
		if len(resp.Files) > 0 {
			diff := resp.Files[0].Diff
			result.Diff = &diff
		}
		applied = append(applied, result)
	}

	switch {
	case len(notApplied) == 0:
		return marshalToolResponse(editFilesResult{
			Status:  editFilesStatusApplied,
			Message: fmt.Sprintf("Applied edits to %d %s.", len(applied), pluralFiles(len(applied))),
			Files:   applied,
		}), nil
	case len(applied) > 0:
		return marshalToolResponse(editFilesResult{
			Status:  editFilesStatusPartial,
			Message: partialEditFilesMessage(len(applied), notApplied),
			Files:   append(notApplied, applied...),
		}), nil
	default:
		return fantasy.NewTextErrorResponse(noneAppliedEditFilesMessage(notApplied)), nil
	}
}

// isAgentResponse reports whether an EditFiles error carries the
// agent's response. A single-file request then wrote nothing: the agent
// validates the file before writing and writes through a temporary file
// and rename, so every error it returns leaves the file unchanged. The
// exception is a panic after the rename, which the agent's recovery
// middleware turns into a 500. An error without a response, such as a
// dropped connection, may follow a completed write.
func isAgentResponse(err error) bool {
	_, ok := codersdk.AsError(err)
	return ok
}

// partialEditFilesMessage summarizes a result where some files were
// applied, naming each file that was not in the order of notApplied.
func partialEditFilesMessage(applied int, notApplied []editFilesFileResult) string {
	var sb strings.Builder
	_, _ = fmt.Fprintf(&sb, "Applied %d %s.", applied, pluralFiles(applied))
	for _, file := range notApplied {
		indexes := formatEditIndexes(file.Edits)
		switch {
		case file.Status == editFilesStatusUnknown:
			_, _ = fmt.Fprintf(&sb, " It is unknown whether %s was applied (%s): re-read %s before resending its edits.", file.Path, indexes, file.Path)
		case file.Error == editFilesInterruptedError:
			_, _ = fmt.Fprintf(&sb, " %s (%s).", interruptedFileSentence(file.Path), indexes)
		case len(file.Edits) == 1:
			_, _ = fmt.Fprintf(&sb, " %s was not applied (%s was not applied): fix and resend only the edits for %s.", file.Path, indexes, file.Path)
		default:
			_, _ = fmt.Fprintf(&sb, " %s was not applied (none of %s were applied): fix and resend only the edits for %s.", file.Path, indexes, file.Path)
		}
	}
	return sb.String()
}

// noneAppliedEditFilesMessage is the error text when no file was
// applied: a heading, then one line per file with its edits and error.
// The heading does not claim that unknown files were not applied.
func noneAppliedEditFilesMessage(files []editFilesFileResult) string {
	heading := editFilesNoneApplied
	if slices.ContainsFunc(files, func(file editFilesFileResult) bool {
		return file.Status == editFilesStatusUnknown
	}) {
		heading = "No files were applied, except that files marked unknown may have been."
	}
	var sb strings.Builder
	_, _ = sb.WriteString(heading)
	for _, file := range files {
		indexes := formatEditIndexes(file.Edits)
		switch {
		case file.Status == editFilesStatusUnknown:
			_, _ = fmt.Fprintf(&sb, "\n- %s (%s): unknown whether applied (%s); re-read it before resending its edits", file.Path, indexes, file.Error)
		case file.Error == editFilesInterruptedError:
			_, _ = fmt.Fprintf(&sb, "\n- %s (%s)", interruptedFileSentence(file.Path), indexes)
		default:
			_, _ = fmt.Fprintf(&sb, "\n- %s (%s): %s", file.Path, indexes, file.Error)
		}
	}
	return sb.String()
}

// editFilesInterruptedError is the error of a file that was not sent
// because the tool call was interrupted. Such a file has nothing to fix,
// so messages name it without a resend instruction.
const editFilesInterruptedError = "not sent because the tool call was interrupted"

func interruptedFileSentence(path string) string {
	return path + " was not applied because the tool call was interrupted"
}

// formatEditIndexes renders indexes as "edits[1], edits[3]".
func formatEditIndexes(indexes []int) string {
	parts := make([]string, 0, len(indexes))
	for _, i := range indexes {
		parts = append(parts, fmt.Sprintf("edits[%d]", i))
	}
	return strings.Join(parts, ", ")
}

// editFilesNoneApplied is the statement in every edit_files error
// result that is known to have written nothing.
const editFilesNoneApplied = "No files were applied."

// File and result statuses in edit_files results.
const (
	editFilesStatusApplied  = "applied"
	editFilesStatusPartial  = "partial"
	editFilesStatusRejected = "rejected"
	editFilesStatusUnknown  = "unknown"
)

// editFilesResult is the edit_files tool result when at least one file
// was applied. Files that were not applied come first.
type editFilesResult struct {
	Status  string                `json:"status"`
	Message string                `json:"message"`
	Files   []editFilesFileResult `json:"files"`
}

// editFilesFileResult is the outcome for one file in editFilesResult.
type editFilesFileResult struct {
	Path   string `json:"path"`
	Status string `json:"status"`
	// Edits holds the edits[i] indexes of a file that was not applied.
	// The agent does not say which edit failed, so it lists them all.
	Edits []int  `json:"edits,omitempty"`
	Error string `json:"error,omitempty"`
	// Diff is the agent's diff for an applied file, nil when the agent
	// returned no per-file result.
	Diff *string `json:"diff,omitempty"`
}

func pluralFiles(n int) string {
	if n == 1 {
		return "file"
	}
	return "files"
}

// rejectEditFiles returns a whole-call rejection decided before any
// edit request reached the agent, so no file was written. reason
// leads with what to change when the model can change anything.
func rejectEditFiles(reason string) fantasy.ToolResponse {
	return fantasy.NewTextErrorResponse(reason + "\n" + editFilesNoneApplied)
}

// agentAPIErrorMessage preserves the agent's actionable message while
// dropping the transport metadata (HTTP method, URL, status code) that
// codersdk.Error.Error() prefixes.
func agentAPIErrorMessage(err error) string {
	sdkErr, ok := codersdk.AsError(err)
	if !ok || sdkErr.Message == "" {
		return err.Error()
	}
	var sb strings.Builder
	_, _ = sb.WriteString(sdkErr.Message)
	if sdkErr.Helper != "" {
		_, _ = sb.WriteString(": " + sdkErr.Helper)
	}
	if sdkErr.Detail != "" {
		_, _ = sb.WriteString(": " + sdkErr.Detail)
	}
	for _, v := range sdkErr.Validations {
		_, _ = sb.WriteString("\n- " + v.Field + ": " + v.Detail)
	}
	return sb.String()
}
