#!/bin/env bash
set -x
kubectl create namespace coder
# ensure ingress works / certs secrets get copied
kubectl label ns coder cert-manager-tls=sync
# needs a postgres db
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install postgres bitnami/postgresql \
	--namespace coder \
	--set auth.username=coder \
	--set auth.password=coder \
	--set auth.database=coder \
	--set persistence.size=10Gi
# deploy via helm for now
helm install coder ./helm/ \
	--namespace coder \
	--values .sharingio/values.yaml
# setup ingress
kubectl apply -f .sharingio/ingress.yaml
# Wait for coder to deploy
kubectl rollout status deployment coder -n coder
kubectl wait -n coder --for=condition=ready pod -l app.kubernetes.io/name=coder
# populate ii or pair as an admin user without logging in
CODER_EMAIL=ii@ii.coop
CODER_PASSWORD=ii
CODER_USERNAME=ii
# export vars to we can emulate a tty with a short expect script
export CODER_EMAIL CODER_PASSWORD CODER_USERNAME
.sharingio/coder-login.exp
#
# echo yes | unbuffer -p coder login https://coder.prerepair.pair.sharing.io
# echo yes | unbuffer -p coder login https://coder.prerepair.pair.sharing.io
# TODO : upload / update the kubernetes template
