// Package namesgenerator generates random names.
//
// This is a fork of github.com/moby/moby/pkg/namesgenerator that uses a
// monotonically increasing counter instead of a random suffix to guarantee
// uniqueness within a process for some functions. This alleviates name
// collisions in parallel tests. It also provides length-limited names
// for limitations commonly found in Coder (e.g. usernames, workspace names).
package namesgenerator

import (
	"math/rand/v2"
	"strconv"
	"strings"
	"sync/atomic"
)

var adjectives = [...]string{
	"admiring",
	"adoring",
	"affectionate",
	"agitated",
	"amazing",
	"angry",
	"awesome",
	"beautiful",
	"blissful",
	"bold",
	"boring",
	"brave",
	"busy",
	"charming",
	"clever",
	"compassionate",
	"competent",
	"condescending",
	"confident",
	"cool",
	"cranky",
	"crazy",
	"dazzling",
	"determined",
	"distracted",
	"dreamy",
	"eager",
	"ecstatic",
	"elastic",
	"elated",
	"elegant",
	"eloquent",
	"epic",
	"exciting",
	"fervent",
	"festive",
	"flamboyant",
	"focused",
	"friendly",
	"frosty",
	"funny",
	"gallant",
	"gifted",
	"goofy",
	"gracious",
	"great",
	"happy",
	"hardcore",
	"heuristic",
	"hopeful",
	"hungry",
	"infallible",
	"inspiring",
	"intelligent",
	"interesting",
	"jolly",
	"jovial",
	"keen",
	"kind",
	"laughing",
	"loving",
	"lucid",
	"magical",
	"modest",
	"musing",
	"mystifying",
	"naughty",
	"nervous",
	"nice",
	"nifty",
	"nostalgic",
	"objective",
	"optimistic",
	"peaceful",
	"pedantic",
	"pensive",
	"practical",
	"priceless",
	"quirky",
	"quizzical",
	"recursing",
	"relaxed",
	"reverent",
	"romantic",
	"sad",
	"serene",
	"sharp",
	"silly",
	"sleepy",
	"stoic",
	"strange",
	"stupefied",
	"suspicious",
	"sweet",
	"tender",
	"thirsty",
	"trusting",
	"unruffled",
	"upbeat",
	"vibrant",
	"vigilant",
	"vigorous",
	"wizardly",
	"wonderful",
	"xenodochial",
	"youthful",
	"zealous",
	"zen",
}

var scientists = [...]string{
	"agnesi",
	"albattani",
	"allen",
	"almeida",
	"antonelli",
	"archimedes",
	"ardinghelli",
	"aryabhata",
	"austin",
	"babbage",
	"banach",
	"banzai",
	"bardeen",
	"bartik",
	"bassi",
	"beaver",
	"bell",
	"benz",
	"bhabha",
	"bhaskara",
	"black",
	"blackburn",
	"blackwell",
	"bohr",
	"booth",
	"borg",
	"bose",
	"bouman",
	"boyd",
	"brahmagupta",
	"brattain",
	"brown",
	"buck",
	"burnell",
	"cannon",
	"carson",
	"cartwright",
	"carver",
	"cerf",
	"chandrasekhar",
	"chaplygin",
	"chatelet",
	"chatterjee",
	"chaum",
	"chebyshev",
	"clarke",
	"cohen",
	"colden",
	"cori",
	"cray",
	"curie",
	"curran",
	"darwin",
	"davinci",
	"dewdney",
	"dhawan",
	"diffie",
	"dijkstra",
	"dirac",
	"driscoll",
	"dubinsky",
	"easley",
	"edison",
	"einstein",
	"elbakyan",
	"elgamal",
	"elion",
	"ellis",
	"engelbart",
	"euclid",
	"euler",
	"faraday",
	"feistel",
	"fermat",
	"fermi",
	"feynman",
	"franklin",
	"gagarin",
	"galileo",
	"galois",
	"ganguly",
	"gates",
	"gauss",
	"germain",
	"goldberg",
	"goldstine",
	"goldwasser",
	"golick",
	"goodall",
	"gould",
	"greider",
	"grothendieck",
	"haibt",
	"hamilton",
	"haslett",
	"hawking",
	"heisenberg",
	"hellman",
	"hermann",
	"herschel",
	"hertz",
	"heyrovsky",
	"hodgkin",
	"hofstadter",
	"hoover",
	"hopper",
	"hugle",
	"hypatia",
	"ishizaka",
	"jackson",
	"jang",
	"jemison",
	"jennings",
	"jepsen",
	"johnson",
	"joliot",
	"jones",
	"kalam",
	"kapitsa",
	"kare",
	"keldysh",
	"keller",
	"kepler",
	"khayyam",
	"khorana",
	"kilby",
	"kirch",
	"knuth",
	"kowalevski",
	"lalande",
	"lamarr",
	"lamport",
	"leakey",
	"leavitt",
	"lederberg",
	"lehmann",
	"lewin",
	"lichterman",
	"liskov",
	"lovelace",
	"lumiere",
	"mahavira",
	"margulis",
	"matsumoto",
	"maxwell",
	"mayer",
	"mccarthy",
	"mcclintock",
	"mclaren",
	"mclean",
	"mcnulty",
	"meitner",
	"mendel",
	"mendeleev",
	"meninsky",
	"merkle",
	"mestorf",
	"mirzakhani",
	"montalcini",
	"moore",
	"morse",
	"moser",
	"murdock",
	"napier",
	"nash",
	"neumann",
	"newton",
	"nightingale",
	"nobel",
	"noether",
	"northcutt",
	"noyce",
	"panini",
	"pare",
	"pascal",
	"pasteur",
	"payne",
	"perlman",
	"pike",
	"poincare",
	"poitras",
	"proskuriakova",
	"ptolemy",
	"raman",
	"ramanujan",
	"rhodes",
	"ride",
	"ritchie",
	"robinson",
	"roentgen",
	"rosalind",
	"rubin",
	"saha",
	"sammet",
	"sanderson",
	"satoshi",
	"shamir",
	"shannon",
	"shaw",
	"shirley",
	"shockley",
	"shtern",
	"sinoussi",
	"snyder",
	"solomon",
	"spence",
	"stonebraker",
	"sutherland",
	"swanson",
	"swartz",
	"swirles",
	"taussig",
	"tesla",
	"tharp",
	"thompson",
	"torvalds",
	"tu",
	"turing",
	"varahamihira",
	"vaughan",
	"villani",
	"visvesvaraya",
	"volhard",
	"wescoff",
	"wilbur",
	"wiles",
	"williams",
	"williamson",
	"wilson",
	"wing",
	"wozniak",
	"wright",
	"wu",
	"yalow",
	"yonath",
	"zhukovsky",
}

// maxNameLen is the maximum length for names in tests. Many places in Coder
// have a 32 character limit for names (usernames, workspace names, etc.).
const maxNameLen = 32

// counter is used to generate unique suffixes for names.
var counter atomic.Int64

// Generate returns a random "adjective_scientist" name without any suffix.
// Use this when you need the base name and will add your own unique suffix.
//
// WARNING: Do not use in tests - the names are not unique and will cause
// collisions. Use GetRandomName or testutil.GetRandomName instead.
func Generate() string {
	//nolint:gosec // Cryptographic randomness is not required for these names.
	return adjectives[rand.IntN(len(adjectives))] + "_" + scientists[rand.IntN(len(scientists))]
}

// GenerateHyphenated is like Generate but uses hyphens instead of underscores.
//
// WARNING: Do not use in tests - the names are not unique and will cause
// collisions. Use GetRandomNameHyphenated or testutil.GetRandomNameHyphenated
// instead.
func GenerateHyphenated() string {
	return strings.ReplaceAll(Generate(), "_", "-")
}

// GetRandomName generates a random name from the list of adjectives and scientists.
// The name is formatted as "adjective_scientist" with a monotonically increasing
// suffix to guarantee uniqueness within the process. It is truncated to maxNameLen
// characters if necessary.
func GetRandomName() string {
	generatedWithSuffix := Generate() + strconv.FormatInt(counter.Add(1), 10)
	return truncate(generatedWithSuffix, maxNameLen)
}

// GetRandomNameHyphenated is like GetRandomName but uses hyphens instead of
// underscores.
func GetRandomNameHyphenated() string {
	generatedWithSuffix := GenerateHyphenated() + strconv.FormatInt(counter.Add(1), 10)
	return truncate(generatedWithSuffix, maxNameLen)
}

// truncate truncates a name to maxLen characters. It assumes the name ends with
// a numeric suffix and preserves it, truncating the base name portion instead.
func truncate(name string, maxLen int) string {
	if len(name) <= maxLen {
		return name
	}
	// Find where the numeric suffix starts.
	suffixStart := len(name)
	for suffixStart > 0 && name[suffixStart-1] >= '0' && name[suffixStart-1] <= '9' {
		suffixStart--
	}
	base := name[:suffixStart]
	suffix := name[suffixStart:]
	truncateAt := maxLen - len(suffix)
	if truncateAt <= 0 {
		return strconv.Itoa(maxLen) // Fallback, shouldn't happen in practice.
	}
	return base[:truncateAt] + suffix
}
