// Code generated by 'guts'. DO NOT EDIT.

// From codersdk/genericslice.go
export interface Bar {
    readonly Bar: string;
}

// From codersdk/genericslice.go
// biome-ignore lint lint/complexity/noUselessTypeConstraint: golang does 'any' for generics, typescript does not like it
export interface Foo<R extends any> {
    readonly Slice: readonly R[];
    readonly TwoD: readonly R[][];
}
