{{- if and .Values.coder.httproute.enable .Values.coder.httproute.httpsRedirect.enable (empty .Values.coder.httproute.httpsRedirect.parentRefs) -}}
{{- fail "coder.httproute.httpsRedirect.parentRefs is required when coder.httproute.httpsRedirect.enable=true" -}}
{{- end -}}

{{- if .Values.coder.httproute.enable }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.coder.httproute.annotations | nindent 4 }}
spec:
  parentRefs:
  {{- with .Values.coder.httproute.parentRefs }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: coder
          # gateway api does not support named ports
          port: 80
  hostnames:
    - {{ .Values.coder.httproute.host | quote }}
    {{- with .Values.coder.httproute.wildcardHost }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.coder.httproute.httpsRedirect.enable }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coder-https-redirect
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.coder.httproute.httpsRedirect.annotations | nindent 4 }}
spec:
  parentRefs:
  {{- with .Values.coder.httproute.httpsRedirect.parentRefs }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - filters:
      - requestRedirect:
          scheme: https
          statusCode: 308
        type: RequestRedirect
      matches:
      - path:
          type: PathPrefix
          value: /
  hostnames:
    - {{ .Values.coder.httproute.host | quote }}
    {{- with .Values.coder.httproute.wildcardHost }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
{{- end }}
