// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: proto/aibridge.proto

package proto

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_proto_aibridge_proto struct{}

func (drpcEncoding_File_proto_aibridge_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_proto_aibridge_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_proto_aibridge_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_proto_aibridge_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_proto_aibridge_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCRecorderClient interface {
	DRPCConn() drpc.Conn

	RecordSession(ctx context.Context, in *RecordSessionRequest) (*RecordSessionResponse, error)
	RecordTokenUsage(ctx context.Context, in *RecordTokenUsageRequest) (*RecordTokenUsageResponse, error)
	RecordPromptUsage(ctx context.Context, in *RecordPromptUsageRequest) (*RecordPromptUsageResponse, error)
	RecordToolUsage(ctx context.Context, in *RecordToolUsageRequest) (*RecordToolUsageResponse, error)
}

type drpcRecorderClient struct {
	cc drpc.Conn
}

func NewDRPCRecorderClient(cc drpc.Conn) DRPCRecorderClient {
	return &drpcRecorderClient{cc}
}

func (c *drpcRecorderClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcRecorderClient) RecordSession(ctx context.Context, in *RecordSessionRequest) (*RecordSessionResponse, error) {
	out := new(RecordSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.Recorder/RecordSession", drpcEncoding_File_proto_aibridge_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcRecorderClient) RecordTokenUsage(ctx context.Context, in *RecordTokenUsageRequest) (*RecordTokenUsageResponse, error) {
	out := new(RecordTokenUsageResponse)
	err := c.cc.Invoke(ctx, "/proto.Recorder/RecordTokenUsage", drpcEncoding_File_proto_aibridge_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcRecorderClient) RecordPromptUsage(ctx context.Context, in *RecordPromptUsageRequest) (*RecordPromptUsageResponse, error) {
	out := new(RecordPromptUsageResponse)
	err := c.cc.Invoke(ctx, "/proto.Recorder/RecordPromptUsage", drpcEncoding_File_proto_aibridge_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcRecorderClient) RecordToolUsage(ctx context.Context, in *RecordToolUsageRequest) (*RecordToolUsageResponse, error) {
	out := new(RecordToolUsageResponse)
	err := c.cc.Invoke(ctx, "/proto.Recorder/RecordToolUsage", drpcEncoding_File_proto_aibridge_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCRecorderServer interface {
	RecordSession(context.Context, *RecordSessionRequest) (*RecordSessionResponse, error)
	RecordTokenUsage(context.Context, *RecordTokenUsageRequest) (*RecordTokenUsageResponse, error)
	RecordPromptUsage(context.Context, *RecordPromptUsageRequest) (*RecordPromptUsageResponse, error)
	RecordToolUsage(context.Context, *RecordToolUsageRequest) (*RecordToolUsageResponse, error)
}

type DRPCRecorderUnimplementedServer struct{}

func (s *DRPCRecorderUnimplementedServer) RecordSession(context.Context, *RecordSessionRequest) (*RecordSessionResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCRecorderUnimplementedServer) RecordTokenUsage(context.Context, *RecordTokenUsageRequest) (*RecordTokenUsageResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCRecorderUnimplementedServer) RecordPromptUsage(context.Context, *RecordPromptUsageRequest) (*RecordPromptUsageResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCRecorderUnimplementedServer) RecordToolUsage(context.Context, *RecordToolUsageRequest) (*RecordToolUsageResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCRecorderDescription struct{}

func (DRPCRecorderDescription) NumMethods() int { return 4 }

func (DRPCRecorderDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/proto.Recorder/RecordSession", drpcEncoding_File_proto_aibridge_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCRecorderServer).
					RecordSession(
						ctx,
						in1.(*RecordSessionRequest),
					)
			}, DRPCRecorderServer.RecordSession, true
	case 1:
		return "/proto.Recorder/RecordTokenUsage", drpcEncoding_File_proto_aibridge_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCRecorderServer).
					RecordTokenUsage(
						ctx,
						in1.(*RecordTokenUsageRequest),
					)
			}, DRPCRecorderServer.RecordTokenUsage, true
	case 2:
		return "/proto.Recorder/RecordPromptUsage", drpcEncoding_File_proto_aibridge_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCRecorderServer).
					RecordPromptUsage(
						ctx,
						in1.(*RecordPromptUsageRequest),
					)
			}, DRPCRecorderServer.RecordPromptUsage, true
	case 3:
		return "/proto.Recorder/RecordToolUsage", drpcEncoding_File_proto_aibridge_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCRecorderServer).
					RecordToolUsage(
						ctx,
						in1.(*RecordToolUsageRequest),
					)
			}, DRPCRecorderServer.RecordToolUsage, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterRecorder(mux drpc.Mux, impl DRPCRecorderServer) error {
	return mux.Register(impl, DRPCRecorderDescription{})
}

type DRPCRecorder_RecordSessionStream interface {
	drpc.Stream
	SendAndClose(*RecordSessionResponse) error
}

type drpcRecorder_RecordSessionStream struct {
	drpc.Stream
}

func (x *drpcRecorder_RecordSessionStream) SendAndClose(m *RecordSessionResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_proto_aibridge_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCRecorder_RecordTokenUsageStream interface {
	drpc.Stream
	SendAndClose(*RecordTokenUsageResponse) error
}

type drpcRecorder_RecordTokenUsageStream struct {
	drpc.Stream
}

func (x *drpcRecorder_RecordTokenUsageStream) SendAndClose(m *RecordTokenUsageResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_proto_aibridge_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCRecorder_RecordPromptUsageStream interface {
	drpc.Stream
	SendAndClose(*RecordPromptUsageResponse) error
}

type drpcRecorder_RecordPromptUsageStream struct {
	drpc.Stream
}

func (x *drpcRecorder_RecordPromptUsageStream) SendAndClose(m *RecordPromptUsageResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_proto_aibridge_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCRecorder_RecordToolUsageStream interface {
	drpc.Stream
	SendAndClose(*RecordToolUsageResponse) error
}

type drpcRecorder_RecordToolUsageStream struct {
	drpc.Stream
}

func (x *drpcRecorder_RecordToolUsageStream) SendAndClose(m *RecordToolUsageResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_proto_aibridge_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
