package chatd

import (
	"context"
	"encoding/json"

	"charm.land/fantasy"
	"charm.land/fantasy/schema"
	"github.com/google/uuid"
	"golang.org/x/sync/errgroup"
	"golang.org/x/xerrors"

	"cdr.dev/slog/v3"
	"github.com/coder/coder/v2/coderd/database"
	"github.com/coder/coder/v2/coderd/x/chatd/chatopenai"
	"github.com/coder/coder/v2/coderd/x/chatd/chatprompt"
	"github.com/coder/coder/v2/coderd/x/chatd/chatprovider"
	"github.com/coder/coder/v2/coderd/x/chatd/chattool"
	"github.com/coder/coder/v2/coderd/x/chatd/mcpclient"
	"github.com/coder/coder/v2/codersdk"
	"github.com/coder/coder/v2/codersdk/agentsdk"
)

// ResolvedChainMode captures the prompt-chaining state derived from persisted
// chat messages.
type ResolvedChainMode struct {
	info                          chatopenai.ChainModeInfo
	PreviousResponseID            string
	ModelConfigID                 uuid.UUID
	ContributingTrailingUserCount int
}

func resolvedChainModeFromInfo(info chatopenai.ChainModeInfo) ResolvedChainMode {
	return ResolvedChainMode{
		info:                          info,
		PreviousResponseID:            info.PreviousResponseID(),
		ModelConfigID:                 info.ModelConfigID(),
		ContributingTrailingUserCount: info.ContributingTrailingUserCount(),
	}
}

func (info ResolvedChainMode) chainModeInfo() chatopenai.ChainModeInfo {
	return info.info
}

// ResolvedAgentRuntimeContext contains the read-only runtime inputs that agent
// authenticated chat endpoints can reuse without dialing workspace agents.
type ResolvedAgentRuntimeContext struct {
	Model                      fantasy.LanguageModel
	ModelConfig                database.ChatModelConfig
	ProviderKeys               chatprovider.ProviderAPIKeys
	CallConfig                 codersdk.ChatModelCallConfig
	ChatMessages               []database.ChatMessage
	PromptMessages             []fantasy.Message
	Instruction                string
	Skills                     []chattool.SkillMeta
	ResolvedUserPrompt         string
	IncludeSubagentInstruction bool
	IncludePlanPathInstruction bool
	ChainMode                  ResolvedChainMode
	ProviderOptions            fantasy.ProviderOptions
	CompactionThresholdPercent int32
	CompactionThresholdSource  string
	ContextLimit               int64
	BuiltInToolDefinitions     []fantasy.Tool
	ProviderToolDefinitions    []fantasy.Tool
	// MCPToolDefinitions stores MCP tool metadata for agent-facing
	// runtime context responses. Each entry carries the prefixed tool
	// name (serverSlug__toolName) as generated by ConnectAll.
	MCPToolDefinitions []agentsdk.ChatRunnerMCPTool
}

type resolvedRuntimeContext struct {
	ResolvedAgentRuntimeContext

	debugEnabled                 bool
	debugProvider                string
	debugModel                   string
	hasContextFiles              bool
	hasPersistedInstructionFiles bool
	persistedAgentID             uuid.UUID
	latestInjectedAgentID        uuid.UUID
	hasLatestInjectedAgent       bool
}

// ResolveAgentRuntimeContext loads the read-only chat runtime context without
// dialing workspace agents or resolving plan paths.
func (p *Server) ResolveAgentRuntimeContext(
	ctx context.Context,
	chat database.Chat,
	logger slog.Logger,
) (ResolvedAgentRuntimeContext, error) {
	runtimeCtx, err := p.resolveRuntimeContext(ctx, chat, logger)
	if err != nil {
		return ResolvedAgentRuntimeContext{}, err
	}
	return runtimeCtx.ResolvedAgentRuntimeContext, nil
}

func (p *Server) resolveRuntimeContext(
	ctx context.Context,
	chat database.Chat,
	logger slog.Logger,
) (resolvedRuntimeContext, error) {
	var runtimeCtx resolvedRuntimeContext

	var (
		model         fantasy.LanguageModel
		modelConfig   database.ChatModelConfig
		providerKeys  chatprovider.ProviderAPIKeys
		callConfig    codersdk.ChatModelCallConfig
		messages      []database.ChatMessage
		debugEnabled  bool
		debugProvider string
		debugModel    string
	)

	var g errgroup.Group
	g.Go(func() error {
		var err error
		model, modelConfig, providerKeys, debugEnabled, debugProvider, debugModel, err = p.resolveChatModel(ctx, chat)
		if err != nil {
			return err
		}
		if len(modelConfig.Options) == 0 {
			return nil
		}
		if err := json.Unmarshal(modelConfig.Options, &callConfig); err != nil {
			return xerrors.Errorf("parse model call config: %w", err)
		}
		return nil
	})
	g.Go(func() error {
		var err error
		messages, err = p.db.GetChatMessagesForPromptByChatID(ctx, chat.ID)
		if err != nil {
			return xerrors.Errorf("get chat messages: %w", err)
		}
		return nil
	})
	if err := g.Wait(); err != nil {
		return runtimeCtx, err
	}

	chainInfo := chatopenai.ResolveChainMode(messages)
	instruction := instructionFromContextFiles(messages)
	skills := skillsFromParts(messages)
	persistedAgentID, hasContextFiles := contextFileAgentID(messages)
	latestInjectedAgentID, hasLatestInjectedAgent := latestContextAgentID(messages)

	var (
		prompt                 []fantasy.Message
		resolvedUserPrompt     string
		compactionThreshold    int32
		hasCompactionThreshold bool
		mcpToolDefinitions     []agentsdk.ChatRunnerMCPTool
	)
	var g2 errgroup.Group
	g2.Go(func() error {
		var err error
		prompt, err = chatprompt.ConvertMessagesWithFiles(ctx, messages, p.chatFileResolver(), logger)
		if err != nil {
			return xerrors.Errorf("build chat prompt: %w", err)
		}
		return nil
	})
	g2.Go(func() error {
		resolvedUserPrompt = p.resolveUserPrompt(ctx, chat.OwnerID)
		return nil
	})
	g2.Go(func() error {
		compactionThreshold, hasCompactionThreshold = p.resolveUserCompactionThreshold(ctx, chat.OwnerID, modelConfig.ID)
		return nil
	})
	g2.Go(func() error {
		if len(chat.MCPServerIDs) == 0 {
			return nil
		}

		configs, err := p.db.GetMCPServerConfigsByIDs(ctx, chat.MCPServerIDs)
		if err != nil {
			return xerrors.Errorf("get MCP server configs: %w", err)
		}
		if len(configs) != len(chat.MCPServerIDs) {
			return xerrors.Errorf(
				"expected %d MCP server configs, got %d",
				len(chat.MCPServerIDs),
				len(configs),
			)
		}

		serverDisplayNames := make(map[uuid.UUID]string, len(configs))
		for _, config := range configs {
			displayName := config.DisplayName
			if displayName == "" {
				displayName = config.Slug
			}
			serverDisplayNames[config.ID] = displayName
		}

		mcpTokens, err := p.db.GetMCPServerUserTokensByUserID(ctx, chat.OwnerID)
		if err != nil {
			return xerrors.Errorf("get MCP server user tokens: %w", err)
		}
		mcpTokens = p.refreshExpiredMCPTokens(ctx, logger, configs, mcpTokens)

		tools, cleanup := mcpclient.ConnectAll(ctx, logger, configs, mcpTokens, chat.OwnerID, p.oidcTokenSource)
		defer cleanup()

		definitions := make([]agentsdk.ChatRunnerMCPTool, 0, len(tools))
		for _, tool := range tools {
			identifier, ok := tool.(mcpclient.MCPToolIdentifier)
			if !ok {
				logger.Warn(ctx, "skipping MCP tool without config identifier",
					slog.F("tool_name", tool.Info().Name),
				)
				continue
			}

			info := tool.Info()
			inputSchema := map[string]any{
				"type":       "object",
				"properties": info.Parameters,
			}
			if len(info.Required) > 0 {
				inputSchema["required"] = info.Required
			}
			schema.Normalize(inputSchema)
			inputSchemaJSON, err := json.Marshal(inputSchema)
			if err != nil {
				return xerrors.Errorf("marshal MCP tool input schema for %q: %w", info.Name, err)
			}

			configID := identifier.MCPServerConfigID()
			serverDisplayName, ok := serverDisplayNames[configID]
			if !ok {
				return xerrors.Errorf("missing display name for MCP server config %s", configID)
			}

			definitions = append(definitions, agentsdk.ChatRunnerMCPTool{
				MCPServerConfigID: configID,
				ToolName:          info.Name,
				Description:       info.Description,
				InputSchema:       inputSchemaJSON,
				ServerDisplayName: serverDisplayName,
			})
		}
		mcpToolDefinitions = definitions
		return nil
	})
	if err := g2.Wait(); err != nil {
		return runtimeCtx, err
	}

	effectiveThreshold := modelConfig.CompressionThreshold
	thresholdSource := "model_default"
	if hasCompactionThreshold {
		effectiveThreshold = compactionThreshold
		thresholdSource = "user_override"
	}

	providerOptions := chatprovider.ProviderOptionsFromChatModelConfig(
		model,
		callConfig.ProviderOptions,
	)
	providerToolDefinitions := buildProviderToolDefinitions(callConfig.ProviderOptions)
	if chat.Mode.Valid && chat.Mode.ChatMode == database.ChatModeComputerUse {
		computerUseProvider, _, _, cuErr := p.computerUseProviderAndModelFromConfig(ctx)
		if cuErr != nil {
			return runtimeCtx, xerrors.Errorf("resolve computer use provider: %w", cuErr)
		}
		tool, cuErr := computerUseProviderToolDefinition(computerUseProvider)
		if cuErr != nil {
			return runtimeCtx, xerrors.Errorf("build computer use provider tool: %w", cuErr)
		}
		providerToolDefinitions = append(providerToolDefinitions, tool)
	}

	runtimeCtx = resolvedRuntimeContext{
		ResolvedAgentRuntimeContext: ResolvedAgentRuntimeContext{
			Model:                      model,
			ModelConfig:                modelConfig,
			ProviderKeys:               providerKeys,
			CallConfig:                 callConfig,
			ChatMessages:               messages,
			PromptMessages:             prompt,
			Instruction:                instruction,
			Skills:                     skills,
			ResolvedUserPrompt:         resolvedUserPrompt,
			IncludeSubagentInstruction: chat.ParentChatID.Valid,
			IncludePlanPathInstruction: !chat.ParentChatID.Valid,
			ChainMode:                  resolvedChainModeFromInfo(chainInfo),
			ProviderOptions:            providerOptions,
			CompactionThresholdPercent: effectiveThreshold,
			CompactionThresholdSource:  thresholdSource,
			ContextLimit:               modelConfig.ContextLimit,
			BuiltInToolDefinitions:     p.builtInToolDefinitions(ctx, chat, skills),
			ProviderToolDefinitions:    providerToolDefinitions,
			MCPToolDefinitions:         mcpToolDefinitions,
		},
		debugEnabled:                 debugEnabled,
		debugProvider:                debugProvider,
		debugModel:                   debugModel,
		hasContextFiles:              hasContextFiles,
		hasPersistedInstructionFiles: hasPersistedInstructionFiles(messages),
		persistedAgentID:             persistedAgentID,
		latestInjectedAgentID:        latestInjectedAgentID,
		hasLatestInjectedAgent:       hasLatestInjectedAgent,
	}
	return runtimeCtx, nil
}

func (p *Server) builtInToolDefinitions(
	ctx context.Context,
	chat database.Chat,
	skills []chattool.SkillMeta,
) []fantasy.Tool {
	return agentToolDefinitions(
		p.definitionOnlyBuiltInTools(ctx, chat, skills),
	)
}

func (p *Server) definitionOnlyBuiltInTools(
	ctx context.Context,
	chat database.Chat,
	skills []chattool.SkillMeta,
) []fantasy.AgentTool {
	tools := []fantasy.AgentTool{
		chattool.ReadFile(chattool.ReadFileOptions{}),
		chattool.WriteFile(chattool.WriteFileOptions{}),
		chattool.EditFiles(chattool.EditFilesOptions{}),
		chattool.Execute(chattool.ExecuteOptions{}),
		chattool.ProcessOutput(chattool.ProcessToolOptions{}),
		chattool.ProcessList(chattool.ProcessToolOptions{}),
		chattool.ProcessSignal(chattool.ProcessToolOptions{}),
	}
	if !chat.ParentChatID.Valid {
		tools = append(tools,
			chattool.ListTemplates(chattool.ListTemplatesOptions{}),
			chattool.ReadTemplate(chattool.ReadTemplateOptions{}),
			chattool.CreateWorkspace(chattool.CreateWorkspaceOptions{}),
			chattool.StartWorkspace(chattool.StartWorkspaceOptions{Logger: p.logger}),
			chattool.ProposePlan(chattool.ProposePlanOptions{}),
		)
		tools = append(tools, p.subagentTools(ctx, nil, uuid.Nil)...)
	}
	if len(skills) > 0 {
		skillOpts := chattool.ReadSkillOptions{
			GetSkills: func() []chattool.SkillMeta {
				return skills
			},
		}
		tools = append(tools,
			chattool.ReadSkill(skillOpts),
			chattool.ReadSkillFile(skillOpts),
		)
	}
	return tools
}

func agentToolDefinitions(tools []fantasy.AgentTool) []fantasy.Tool {
	prepared := make([]fantasy.Tool, 0, len(tools))
	for _, tool := range tools {
		info := tool.Info()
		inputSchema := map[string]any{
			"type":       "object",
			"properties": info.Parameters,
		}
		if len(info.Required) > 0 {
			inputSchema["required"] = info.Required
		}
		schema.Normalize(inputSchema)
		prepared = append(prepared, fantasy.FunctionTool{
			Name:            info.Name,
			Description:     info.Description,
			InputSchema:     inputSchema,
			ProviderOptions: tool.ProviderOptions(),
		})
	}
	return prepared
}

func buildProviderToolDefinitions(
	options *codersdk.ChatModelProviderOptions,
) []fantasy.Tool {
	if options == nil {
		return nil
	}
	providerTools := buildProviderTools(options)
	definitions := make([]fantasy.Tool, 0, len(providerTools))
	for _, tool := range providerTools {
		definitions = append(definitions, tool.Definition)
	}
	return definitions
}

func computerUseProviderToolDefinition(provider string) (fantasy.Tool, error) {
	desktopGeometry := chattool.DefaultComputerUseDesktopGeometry(provider)
	return chattool.ComputerUseProviderTool(
		provider,
		desktopGeometry.DeclaredWidth,
		desktopGeometry.DeclaredHeight,
	)
}
