// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coder/coder/v2/coderd/gitsync (interfaces: EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination ./publisher.go -package gitsyncmock github.com/coder/coder/v2/coderd/gitsync EventPublisher
//

// Package gitsyncmock is a generated GoMock package.
package gitsyncmock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishDiffStatusChange mocks base method.
func (m *MockEventPublisher) PublishDiffStatusChange(ctx context.Context, chatID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDiffStatusChange", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDiffStatusChange indicates an expected call of PublishDiffStatusChange.
func (mr *MockEventPublisherMockRecorder) PublishDiffStatusChange(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDiffStatusChange", reflect.TypeOf((*MockEventPublisher)(nil).PublishDiffStatusChange), ctx, chatID)
}
