name: "Install syft"
description: |
  Downloads Syft to the Action tool cache and provides a reference.
runs:
  using: "composite"
  steps:
    - name: Install syft
      uses: anchore/sbom-action/download-syft@e11c554f704a0b820cbf07f96cde0dc0f7c677dd # v0.20.0
      with:
        syft-version: "v1.26.1"
