import { defineConfig, defineDocs } from "fumadocs-mdx/config";
import { metaSchema, pageSchema } from "fumadocs-core/source/schema";
import { remarkSteps } from "fumadocs-core/mdx-plugins";
import rehypeRaw from "rehype-raw";
import { remarkGithubCallouts } from "./src/mdx-plugins/remark-github-callouts";
import { remarkCoderTabs } from "./src/mdx-plugins/remark-coder-tabs";
import { remarkDetailsAccordion } from "./src/mdx-plugins/remark-details-accordion";
import { remarkCodeMeta } from "./src/mdx-plugins/remark-code-meta";
import { rehypeStepTocNumbers } from "./src/mdx-plugins/rehype-step-toc-numbers";

// The content under content/docs is generated by scripts/sync-docs.mjs from the
// coder/coder docs corpus (see the sync step). See
// https://fumadocs.dev/docs/mdx/collections for schema customization.
export const docs = defineDocs({
	dir: "content/docs",
	docs: {
		schema: pageSchema,
		postprocess: {
			includeProcessedMarkdown: true,
		},
	},
	meta: {
		schema: metaSchema,
	},
});

export default defineConfig({
	mdxOptions: {
		// Rewrite GitHub-style alerts (`> [!NOTE]`) into `Callout`,
		// `<div class="tabs">` blocks into `Tabs`/`Tab`, and `<details>`/`<summary>`
		// blocks into `Accordions`. All run before the default plugins
		// (structure/TOC) and the rehype stage so downstream sees the rewritten
		// tree. Tabs runs before the accordion pass so a tabs block inside a
		// `<details>` is converted first, then wrapped. `remarkCodeMeta` runs after
		// those (still before the rehype stage) to carry code-fence meta such as
		// `title="main.tf"` onto the `<code>` element so it survives `rehype-raw`.
		// `remarkSteps` (Fumadocs core) groups consecutive `## Title [step]`
		// headings into a numbered `.fd-steps` structure. The `[step]` markers are
		// baked into the synced source by `normalizeStepHeadings` (see
		// scripts/lib/transform.mjs), so no custom step plugin runs here.
		// Prepending is safe: these plugins match core Markdown blockquotes and raw
		// HTML nodes, independent of any default plugin.
		remarkPlugins: (v) => [
			remarkGithubCallouts,
			remarkCoderTabs,
			remarkDetailsAccordion,
			remarkCodeMeta,
			remarkSteps,
			...v,
		],
		// Doc images are copied into the bundle by the sync step and referenced by
		// root-absolute paths (/images/...). Disable Fumadocs' remark-image, which
		// otherwise reads every image to inject width/height and hard-fails on any
		// missing file; the images render as plain <img> (see src/components/mdx.tsx)
		// and the bundle is served unoptimized.
		remarkImageOptions: false,
		// The corpus is emitted as plain Markdown (.md), which Fumadocs compiles
		// with NO JSX/expression parsing. By default that also DROPS raw HTML
		// blocks (the corpus has ~30 <table> blocks, <details>, etc.). Keep raw
		// HTML and parse it with rehype-raw so those render like GitHub shows
		// them. rehype-raw runs first so the code highlighter sees a clean tree.
		remarkRehypeOptions: { allowDangerousHtml: true },
		rehypePlugins: (v) => [
			// Fumadocs injects MDX ESM/expression nodes (frontmatter exports, TOC,
			// structuredData) even for .md files. rehype-raw must pass those
			// through untouched instead of trying to serialise them as HTML.
			[
				rehypeRaw,
				{
					passThrough: [
						"mdxjsEsm",
						"mdxFlowExpression",
						"mdxTextExpression",
						"mdxJsxFlowElement",
						"mdxJsxTextElement",
					],
				},
			],
			// `rehype-raw` above reparses the tree and turns the numeric
			// `data-fd-step` that `remarkSteps` set into a string (renaming the key
			// to camelCase), which makes the default `rehypeToc` drop step numbers
			// from the TOC. Restore it to a number before the default plugins (which
			// include `rehypeToc`) run.
			rehypeStepTocNumbers,
			...v,
		],
		// The coder/coder corpus uses code-fence languages that Shiki does not
		// bundle (env, caddyfile, promql, output, none, url, ...). Without a
		// fallback, Shiki throws a hard error and fails the whole build. A
		// fallback language renders unknown fences as plain text instead.
		// `lazy` (the default) loads recognised languages on demand.
		rehypeCodeOptions: {
			lazy: true,
			fallbackLanguage: "text",
			themes: {
				light: "github-light",
				dark: "github-dark",
			},
		},
	},
});
