import { v4 as uuidv4 } from "uuid";

/**
 * Generate a random UUID (version 4).
 */
export const generateUUID = (): string => uuidv4();

/**
 * Generate a random hexadecimal string from the specified number of bytes.
 */
const generateRandomString = (bytes: number): string => {
	const byteArr = crypto.getRandomValues(new Uint8Array(bytes));
	return [...byteArr]
		.map((byte) => byte.toString(16).padStart(2, "0"))
		.join("");
};

/**
 * Generate a cryptographically secure random string using the specified number
 * of bytes then encode with base64.
 *
 * Base64 encodes 6 bits per character and pads with = so the length will not
 * equal the number of randomly generated bytes.
 * @see <https://developer.mozilla.org/en-US/docs/Glossary/Base64#encoded_size_increase>
 */
export const generateRandomBase64String = (bytes: number): string => {
	return btoa(generateRandomString(bytes));
};

/**
 * Generate a 16-byte (32-character) hexadecimal string for identifying
 * workspace connection sessions.
 */
export const generateConnectionSessionId = (): string => {
	return generateRandomString(16);
};
