package loadtestutil

import (
	"context"
	"fmt"
	"strings"
	"time"

	"golang.org/x/xerrors"

	"github.com/coder/coder/v2/codersdk"
)

// ReuseUser is an existing scaletest user selected for reuse, together with a
// freshly minted session token authenticating as that user.
type ReuseUser struct {
	User         codersdk.User
	SessionToken string
}

// InsufficientUsersError is returned by SelectReuseUsers when the pool does not
// contain enough matching users. Callers can errors.As it to append an
// actionable hint, such as the create-users command that provisions a pool.
type InsufficientUsersError struct {
	Found int
	Need  int
}

func (e *InsufficientUsersError) Error() string {
	return fmt.Sprintf("not enough scaletest users to reuse: found %d, need %d", e.Found, e.Need)
}

// ReuseSearchPrefix builds the username search prefix for a reuse pool. The
// mandatory "scaletest-" root is always kept so selection matches the users that
// create-users provisions; usernameInfix, when set, narrows to a specific pool
// (for example "notif" selects scaletest-notif-<random>-<id>), isolating this
// run from other load generators that reuse scaletest users concurrently.
func ReuseSearchPrefix(usernameInfix string) string {
	prefix := ScaleTestPrefix + "-"
	if usernameInfix != "" {
		prefix += usernameInfix + "-"
	}
	return prefix
}

// SelectReuseUsers lists the scaletest users in the pool identified by
// usernameInfix, keeps those matching filter (a nil filter matches any user),
// and returns the first count of them. It performs only read requests and mints
// no tokens; use MintReuseTokens for that. It returns an *InsufficientUsersError
// when fewer than count users match, so callers can select every group they need
// before minting any tokens.
func SelectReuseUsers(ctx context.Context, client *codersdk.Client, usernameInfix string, count int, filter func(codersdk.User) bool) ([]codersdk.User, error) {
	users, err := GetScaletestUsersWithPrefix(ctx, client, ReuseSearchPrefix(usernameInfix))
	if err != nil {
		return nil, xerrors.Errorf("list scaletest users: %w", err)
	}

	matched := users
	if filter != nil {
		matched = make([]codersdk.User, 0, len(users))
		for _, u := range users {
			if filter(u) {
				matched = append(matched, u)
			}
		}
	}

	if len(matched) < count {
		return nil, &InsufficientUsersError{Found: len(matched), Need: count}
	}

	return matched[:count], nil
}

// MintReuseTokens mints a session token with the given lifetime for each user
// and pairs it with the user. Token names are auto-generated by the server. It
// performs writes; if it fails partway, previously minted tokens are left to
// expire via their lifetime.
func MintReuseTokens(ctx context.Context, client *codersdk.Client, users []codersdk.User, lifetime time.Duration) ([]ReuseUser, error) {
	reuse := make([]ReuseUser, 0, len(users))
	for _, u := range users {
		res, err := client.CreateToken(ctx, u.ID.String(), codersdk.CreateTokenRequest{
			Lifetime: lifetime,
		})
		if err != nil {
			return nil, xerrors.Errorf("mint token for user %q: %w", u.Username, err)
		}
		reuse = append(reuse, ReuseUser{User: u, SessionToken: res.Key})
	}
	return reuse, nil
}

// UserHasRole reports whether the user holds the named role.
func UserHasRole(u codersdk.User, roleName string) bool {
	for _, role := range u.Roles {
		if role.Name == roleName {
			return true
		}
	}
	return false
}

// GetScaletestUsers returns all scaletest users in the default pool.
func GetScaletestUsers(ctx context.Context, client *codersdk.Client) ([]codersdk.User, error) {
	return GetScaletestUsersWithPrefix(ctx, client, ScaleTestPrefix+"-")
}

// GetScaletestUsersWithPrefix returns scaletest users whose username starts with
// the given full prefix. The prefix partitions users into disjoint pools (for
// example per load generator) so that concurrent reuse runs select
// non-overlapping users.
func GetScaletestUsersWithPrefix(ctx context.Context, client *codersdk.Client, prefix string) ([]codersdk.User, error) {
	var (
		pageNumber = 0
		limit      = 100
		users      []codersdk.User
	)

	for {
		page, err := client.Users(ctx, codersdk.UsersRequest{
			Search: prefix,
			Pagination: codersdk.Pagination{
				Offset: pageNumber * limit,
				Limit:  limit,
			},
		})
		if err != nil {
			return nil, xerrors.Errorf("fetch scaletest users page %d: %w", pageNumber, err)
		}

		pageNumber++
		if len(page.Users) == 0 {
			break
		}

		users = append(users, FilterScaletestUsersByPrefix(page.Users, prefix)...)
	}

	return users, nil
}

// FilterScaletestUsersByPrefix returns the users whose username starts with
// prefix and that look like scaletest users. It is the in-memory selection
// behind GetScaletestUsersWithPrefix. The username prefix guard matters because
// the users search matches the term in several fields, not just the username.
func FilterScaletestUsersByPrefix(users []codersdk.User, prefix string) []codersdk.User {
	filtered := make([]codersdk.User, 0, len(users))
	for _, u := range users {
		if strings.HasPrefix(u.Username, prefix) && IsScaleTestUser(u.Username, u.Email) {
			filtered = append(filtered, u)
		}
	}
	return filtered
}
