// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tailnet/proto/tailnet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoordinateResponse_PeerUpdate_Kind int32

const (
	CoordinateResponse_PeerUpdate_KIND_UNSPECIFIED    CoordinateResponse_PeerUpdate_Kind = 0
	CoordinateResponse_PeerUpdate_NODE                CoordinateResponse_PeerUpdate_Kind = 1
	CoordinateResponse_PeerUpdate_DISCONNECTED        CoordinateResponse_PeerUpdate_Kind = 2
	CoordinateResponse_PeerUpdate_LOST                CoordinateResponse_PeerUpdate_Kind = 3
	CoordinateResponse_PeerUpdate_READY_FOR_HANDSHAKE CoordinateResponse_PeerUpdate_Kind = 4
)

// Enum value maps for CoordinateResponse_PeerUpdate_Kind.
var (
	CoordinateResponse_PeerUpdate_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "NODE",
		2: "DISCONNECTED",
		3: "LOST",
		4: "READY_FOR_HANDSHAKE",
	}
	CoordinateResponse_PeerUpdate_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":    0,
		"NODE":                1,
		"DISCONNECTED":        2,
		"LOST":                3,
		"READY_FOR_HANDSHAKE": 4,
	}
)

func (x CoordinateResponse_PeerUpdate_Kind) Enum() *CoordinateResponse_PeerUpdate_Kind {
	p := new(CoordinateResponse_PeerUpdate_Kind)
	*p = x
	return p
}

func (x CoordinateResponse_PeerUpdate_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoordinateResponse_PeerUpdate_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_tailnet_proto_tailnet_proto_enumTypes[0].Descriptor()
}

func (CoordinateResponse_PeerUpdate_Kind) Type() protoreflect.EnumType {
	return &file_tailnet_proto_tailnet_proto_enumTypes[0]
}

func (x CoordinateResponse_PeerUpdate_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoordinateResponse_PeerUpdate_Kind.Descriptor instead.
func (CoordinateResponse_PeerUpdate_Kind) EnumDescriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{6, 0, 0}
}

type IPFields_IPClass int32

const (
	IPFields_PUBLIC     IPFields_IPClass = 0
	IPFields_PRIVATE    IPFields_IPClass = 1
	IPFields_LINK_LOCAL IPFields_IPClass = 2
	IPFields_LOOPBACK   IPFields_IPClass = 3
)

// Enum value maps for IPFields_IPClass.
var (
	IPFields_IPClass_name = map[int32]string{
		0: "PUBLIC",
		1: "PRIVATE",
		2: "LINK_LOCAL",
		3: "LOOPBACK",
	}
	IPFields_IPClass_value = map[string]int32{
		"PUBLIC":     0,
		"PRIVATE":    1,
		"LINK_LOCAL": 2,
		"LOOPBACK":   3,
	}
)

func (x IPFields_IPClass) Enum() *IPFields_IPClass {
	p := new(IPFields_IPClass)
	*p = x
	return p
}

func (x IPFields_IPClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPFields_IPClass) Descriptor() protoreflect.EnumDescriptor {
	return file_tailnet_proto_tailnet_proto_enumTypes[1].Descriptor()
}

func (IPFields_IPClass) Type() protoreflect.EnumType {
	return &file_tailnet_proto_tailnet_proto_enumTypes[1]
}

func (x IPFields_IPClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPFields_IPClass.Descriptor instead.
func (IPFields_IPClass) EnumDescriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{7, 0}
}

type TelemetryEvent_Status int32

const (
	TelemetryEvent_CONNECTED    TelemetryEvent_Status = 0
	TelemetryEvent_DISCONNECTED TelemetryEvent_Status = 1
)

// Enum value maps for TelemetryEvent_Status.
var (
	TelemetryEvent_Status_name = map[int32]string{
		0: "CONNECTED",
		1: "DISCONNECTED",
	}
	TelemetryEvent_Status_value = map[string]int32{
		"CONNECTED":    0,
		"DISCONNECTED": 1,
	}
)

func (x TelemetryEvent_Status) Enum() *TelemetryEvent_Status {
	p := new(TelemetryEvent_Status)
	*p = x
	return p
}

func (x TelemetryEvent_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryEvent_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tailnet_proto_tailnet_proto_enumTypes[2].Descriptor()
}

func (TelemetryEvent_Status) Type() protoreflect.EnumType {
	return &file_tailnet_proto_tailnet_proto_enumTypes[2]
}

func (x TelemetryEvent_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryEvent_Status.Descriptor instead.
func (TelemetryEvent_Status) EnumDescriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{9, 0}
}

type TelemetryEvent_ClientType int32

const (
	TelemetryEvent_CLI     TelemetryEvent_ClientType = 0
	TelemetryEvent_AGENT   TelemetryEvent_ClientType = 1
	TelemetryEvent_CODERD  TelemetryEvent_ClientType = 2
	TelemetryEvent_WSPROXY TelemetryEvent_ClientType = 3
)

// Enum value maps for TelemetryEvent_ClientType.
var (
	TelemetryEvent_ClientType_name = map[int32]string{
		0: "CLI",
		1: "AGENT",
		2: "CODERD",
		3: "WSPROXY",
	}
	TelemetryEvent_ClientType_value = map[string]int32{
		"CLI":     0,
		"AGENT":   1,
		"CODERD":  2,
		"WSPROXY": 3,
	}
)

func (x TelemetryEvent_ClientType) Enum() *TelemetryEvent_ClientType {
	p := new(TelemetryEvent_ClientType)
	*p = x
	return p
}

func (x TelemetryEvent_ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryEvent_ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_tailnet_proto_tailnet_proto_enumTypes[3].Descriptor()
}

func (TelemetryEvent_ClientType) Type() protoreflect.EnumType {
	return &file_tailnet_proto_tailnet_proto_enumTypes[3]
}

func (x TelemetryEvent_ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryEvent_ClientType.Descriptor instead.
func (TelemetryEvent_ClientType) EnumDescriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{9, 1}
}

type Workspace_Status int32

const (
	Workspace_UNKNOWN   Workspace_Status = 0
	Workspace_PENDING   Workspace_Status = 1
	Workspace_STARTING  Workspace_Status = 2
	Workspace_RUNNING   Workspace_Status = 3
	Workspace_STOPPING  Workspace_Status = 4
	Workspace_STOPPED   Workspace_Status = 5
	Workspace_FAILED    Workspace_Status = 6
	Workspace_CANCELING Workspace_Status = 7
	Workspace_CANCELED  Workspace_Status = 8
	Workspace_DELETING  Workspace_Status = 9
	Workspace_DELETED   Workspace_Status = 10
)

// Enum value maps for Workspace_Status.
var (
	Workspace_Status_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "PENDING",
		2:  "STARTING",
		3:  "RUNNING",
		4:  "STOPPING",
		5:  "STOPPED",
		6:  "FAILED",
		7:  "CANCELING",
		8:  "CANCELED",
		9:  "DELETING",
		10: "DELETED",
	}
	Workspace_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"STARTING":  2,
		"RUNNING":   3,
		"STOPPING":  4,
		"STOPPED":   5,
		"FAILED":    6,
		"CANCELING": 7,
		"CANCELED":  8,
		"DELETING":  9,
		"DELETED":   10,
	}
)

func (x Workspace_Status) Enum() *Workspace_Status {
	p := new(Workspace_Status)
	*p = x
	return p
}

func (x Workspace_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Workspace_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tailnet_proto_tailnet_proto_enumTypes[4].Descriptor()
}

func (Workspace_Status) Type() protoreflect.EnumType {
	return &file_tailnet_proto_tailnet_proto_enumTypes[4]
}

func (x Workspace_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Workspace_Status.Descriptor instead.
func (Workspace_Status) EnumDescriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{14, 0}
}

type DERPMap struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	HomeParams    *DERPMap_HomeParams       `protobuf:"bytes,1,opt,name=home_params,json=homeParams,proto3" json:"home_params,omitempty"`
	Regions       map[int64]*DERPMap_Region `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DERPMap) Reset() {
	*x = DERPMap{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DERPMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DERPMap) ProtoMessage() {}

func (x *DERPMap) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DERPMap.ProtoReflect.Descriptor instead.
func (*DERPMap) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{0}
}

func (x *DERPMap) GetHomeParams() *DERPMap_HomeParams {
	if x != nil {
		return x.HomeParams
	}
	return nil
}

func (x *DERPMap) GetRegions() map[int64]*DERPMap_Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

type StreamDERPMapsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDERPMapsRequest) Reset() {
	*x = StreamDERPMapsRequest{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDERPMapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDERPMapsRequest) ProtoMessage() {}

func (x *StreamDERPMapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDERPMapsRequest.ProtoReflect.Descriptor instead.
func (*StreamDERPMapsRequest) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{1}
}

// defined in tailnet/coordinator.go
type Node struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AsOf                *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	Key                 []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Disco               string                 `protobuf:"bytes,4,opt,name=disco,proto3" json:"disco,omitempty"`
	PreferredDerp       int32                  `protobuf:"varint,5,opt,name=preferred_derp,json=preferredDerp,proto3" json:"preferred_derp,omitempty"`
	DerpLatency         map[string]float64     `protobuf:"bytes,6,rep,name=derp_latency,json=derpLatency,proto3" json:"derp_latency,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	DerpForcedWebsocket map[int32]string       `protobuf:"bytes,7,rep,name=derp_forced_websocket,json=derpForcedWebsocket,proto3" json:"derp_forced_websocket,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Addresses           []string               `protobuf:"bytes,8,rep,name=addresses,proto3" json:"addresses,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,9,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Endpoints           []string               `protobuf:"bytes,10,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Human readable description of the connection, e.g. "Coder Server" or "VSCode IDE Plugin"
	ShortDescription string `protobuf:"bytes,11,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	// Peer's self-reported hostname. For informational / display purposes only
	Hostname string `protobuf:"bytes,12,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Client operating system (e.g., "linux", "darwin", "windows").
	Os            string `protobuf:"bytes,13,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

func (x *Node) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Node) GetDisco() string {
	if x != nil {
		return x.Disco
	}
	return ""
}

func (x *Node) GetPreferredDerp() int32 {
	if x != nil {
		return x.PreferredDerp
	}
	return 0
}

func (x *Node) GetDerpLatency() map[string]float64 {
	if x != nil {
		return x.DerpLatency
	}
	return nil
}

func (x *Node) GetDerpForcedWebsocket() map[int32]string {
	if x != nil {
		return x.DerpForcedWebsocket
	}
	return nil
}

func (x *Node) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Node) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *Node) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Node) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Node) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Node) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type RefreshResumeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResumeTokenRequest) Reset() {
	*x = RefreshResumeTokenRequest{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResumeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResumeTokenRequest) ProtoMessage() {}

func (x *RefreshResumeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResumeTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshResumeTokenRequest) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{3}
}

type RefreshResumeTokenResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Token     string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshIn *durationpb.Duration   `protobuf:"bytes,2,opt,name=refresh_in,json=refreshIn,proto3" json:"refresh_in,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// peer_id is the unique identifier for this peer, assigned by the server.
	// Clients should use this to derive their tailnet IP addresses via
	// ServicePrefix.PrefixFromUUID(peerID) before creating their tailnet.Conn.
	PeerId        []byte `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // UUID (16 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResumeTokenResponse) Reset() {
	*x = RefreshResumeTokenResponse{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResumeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResumeTokenResponse) ProtoMessage() {}

func (x *RefreshResumeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResumeTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshResumeTokenResponse) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshResumeTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshResumeTokenResponse) GetRefreshIn() *durationpb.Duration {
	if x != nil {
		return x.RefreshIn
	}
	return nil
}

func (x *RefreshResumeTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RefreshResumeTokenResponse) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

type CoordinateRequest struct {
	state             protoimpl.MessageState                 `protogen:"open.v1"`
	UpdateSelf        *CoordinateRequest_UpdateSelf          `protobuf:"bytes,1,opt,name=update_self,json=updateSelf,proto3" json:"update_self,omitempty"`
	Disconnect        *CoordinateRequest_Disconnect          `protobuf:"bytes,2,opt,name=disconnect,proto3" json:"disconnect,omitempty"`
	AddTunnel         *CoordinateRequest_Tunnel              `protobuf:"bytes,3,opt,name=add_tunnel,json=addTunnel,proto3" json:"add_tunnel,omitempty"`
	RemoveTunnel      *CoordinateRequest_Tunnel              `protobuf:"bytes,4,opt,name=remove_tunnel,json=removeTunnel,proto3" json:"remove_tunnel,omitempty"`
	ReadyForHandshake []*CoordinateRequest_ReadyForHandshake `protobuf:"bytes,5,rep,name=ready_for_handshake,json=readyForHandshake,proto3" json:"ready_for_handshake,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CoordinateRequest) Reset() {
	*x = CoordinateRequest{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRequest) ProtoMessage() {}

func (x *CoordinateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRequest.ProtoReflect.Descriptor instead.
func (*CoordinateRequest) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{5}
}

func (x *CoordinateRequest) GetUpdateSelf() *CoordinateRequest_UpdateSelf {
	if x != nil {
		return x.UpdateSelf
	}
	return nil
}

func (x *CoordinateRequest) GetDisconnect() *CoordinateRequest_Disconnect {
	if x != nil {
		return x.Disconnect
	}
	return nil
}

func (x *CoordinateRequest) GetAddTunnel() *CoordinateRequest_Tunnel {
	if x != nil {
		return x.AddTunnel
	}
	return nil
}

func (x *CoordinateRequest) GetRemoveTunnel() *CoordinateRequest_Tunnel {
	if x != nil {
		return x.RemoveTunnel
	}
	return nil
}

func (x *CoordinateRequest) GetReadyForHandshake() []*CoordinateRequest_ReadyForHandshake {
	if x != nil {
		return x.ReadyForHandshake
	}
	return nil
}

type CoordinateResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	PeerUpdates   []*CoordinateResponse_PeerUpdate `protobuf:"bytes,1,rep,name=peer_updates,json=peerUpdates,proto3" json:"peer_updates,omitempty"`
	Error         string                           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateResponse) Reset() {
	*x = CoordinateResponse{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateResponse) ProtoMessage() {}

func (x *CoordinateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateResponse.ProtoReflect.Descriptor instead.
func (*CoordinateResponse) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{6}
}

func (x *CoordinateResponse) GetPeerUpdates() []*CoordinateResponse_PeerUpdate {
	if x != nil {
		return x.PeerUpdates
	}
	return nil
}

func (x *CoordinateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IPFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Class         IPFields_IPClass       `protobuf:"varint,2,opt,name=class,proto3,enum=coder.tailnet.v2.IPFields_IPClass" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPFields) Reset() {
	*x = IPFields{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPFields) ProtoMessage() {}

func (x *IPFields) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPFields.ProtoReflect.Descriptor instead.
func (*IPFields) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{7}
}

func (x *IPFields) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IPFields) GetClass() IPFields_IPClass {
	if x != nil {
		return x.Class
	}
	return IPFields_PUBLIC
}

type Netcheck struct {
	state                 protoimpl.MessageState         `protogen:"open.v1"`
	UDP                   bool                           `protobuf:"varint,1,opt,name=UDP,proto3" json:"UDP,omitempty"`
	IPv6                  bool                           `protobuf:"varint,2,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
	IPv4                  bool                           `protobuf:"varint,3,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	IPv6CanSend           bool                           `protobuf:"varint,4,opt,name=IPv6CanSend,proto3" json:"IPv6CanSend,omitempty"`
	IPv4CanSend           bool                           `protobuf:"varint,5,opt,name=IPv4CanSend,proto3" json:"IPv4CanSend,omitempty"`
	ICMPv4                bool                           `protobuf:"varint,6,opt,name=ICMPv4,proto3" json:"ICMPv4,omitempty"`
	OSHasIPv6             *wrapperspb.BoolValue          `protobuf:"bytes,7,opt,name=OSHasIPv6,proto3" json:"OSHasIPv6,omitempty"`
	MappingVariesByDestIP *wrapperspb.BoolValue          `protobuf:"bytes,8,opt,name=MappingVariesByDestIP,proto3" json:"MappingVariesByDestIP,omitempty"`
	HairPinning           *wrapperspb.BoolValue          `protobuf:"bytes,9,opt,name=HairPinning,proto3" json:"HairPinning,omitempty"`
	UPnP                  *wrapperspb.BoolValue          `protobuf:"bytes,10,opt,name=UPnP,proto3" json:"UPnP,omitempty"`
	PMP                   *wrapperspb.BoolValue          `protobuf:"bytes,11,opt,name=PMP,proto3" json:"PMP,omitempty"`
	PCP                   *wrapperspb.BoolValue          `protobuf:"bytes,12,opt,name=PCP,proto3" json:"PCP,omitempty"`
	PreferredDERP         int64                          `protobuf:"varint,13,opt,name=PreferredDERP,proto3" json:"PreferredDERP,omitempty"` // 0 for unknown
	RegionV4Latency       map[int64]*durationpb.Duration `protobuf:"bytes,14,rep,name=RegionV4Latency,proto3" json:"RegionV4Latency,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegionV6Latency       map[int64]*durationpb.Duration `protobuf:"bytes,15,rep,name=RegionV6Latency,proto3" json:"RegionV6Latency,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GlobalV4              *Netcheck_NetcheckIP           `protobuf:"bytes,17,opt,name=GlobalV4,proto3" json:"GlobalV4,omitempty"`
	GlobalV6              *Netcheck_NetcheckIP           `protobuf:"bytes,18,opt,name=GlobalV6,proto3" json:"GlobalV6,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Netcheck) Reset() {
	*x = Netcheck{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Netcheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Netcheck) ProtoMessage() {}

func (x *Netcheck) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Netcheck.ProtoReflect.Descriptor instead.
func (*Netcheck) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{8}
}

func (x *Netcheck) GetUDP() bool {
	if x != nil {
		return x.UDP
	}
	return false
}

func (x *Netcheck) GetIPv6() bool {
	if x != nil {
		return x.IPv6
	}
	return false
}

func (x *Netcheck) GetIPv4() bool {
	if x != nil {
		return x.IPv4
	}
	return false
}

func (x *Netcheck) GetIPv6CanSend() bool {
	if x != nil {
		return x.IPv6CanSend
	}
	return false
}

func (x *Netcheck) GetIPv4CanSend() bool {
	if x != nil {
		return x.IPv4CanSend
	}
	return false
}

func (x *Netcheck) GetICMPv4() bool {
	if x != nil {
		return x.ICMPv4
	}
	return false
}

func (x *Netcheck) GetOSHasIPv6() *wrapperspb.BoolValue {
	if x != nil {
		return x.OSHasIPv6
	}
	return nil
}

func (x *Netcheck) GetMappingVariesByDestIP() *wrapperspb.BoolValue {
	if x != nil {
		return x.MappingVariesByDestIP
	}
	return nil
}

func (x *Netcheck) GetHairPinning() *wrapperspb.BoolValue {
	if x != nil {
		return x.HairPinning
	}
	return nil
}

func (x *Netcheck) GetUPnP() *wrapperspb.BoolValue {
	if x != nil {
		return x.UPnP
	}
	return nil
}

func (x *Netcheck) GetPMP() *wrapperspb.BoolValue {
	if x != nil {
		return x.PMP
	}
	return nil
}

func (x *Netcheck) GetPCP() *wrapperspb.BoolValue {
	if x != nil {
		return x.PCP
	}
	return nil
}

func (x *Netcheck) GetPreferredDERP() int64 {
	if x != nil {
		return x.PreferredDERP
	}
	return 0
}

func (x *Netcheck) GetRegionV4Latency() map[int64]*durationpb.Duration {
	if x != nil {
		return x.RegionV4Latency
	}
	return nil
}

func (x *Netcheck) GetRegionV6Latency() map[int64]*durationpb.Duration {
	if x != nil {
		return x.RegionV6Latency
	}
	return nil
}

func (x *Netcheck) GetGlobalV4() *Netcheck_NetcheckIP {
	if x != nil {
		return x.GlobalV4
	}
	return nil
}

func (x *Netcheck) GetGlobalV6() *Netcheck_NetcheckIP {
	if x != nil {
		return x.GlobalV6
	}
	return nil
}

type TelemetryEvent struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Id              []byte                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time            *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Application     string                      `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"`
	Status          TelemetryEvent_Status       `protobuf:"varint,4,opt,name=status,proto3,enum=coder.tailnet.v2.TelemetryEvent_Status" json:"status,omitempty"`
	ClientType      TelemetryEvent_ClientType   `protobuf:"varint,6,opt,name=client_type,json=clientType,proto3,enum=coder.tailnet.v2.TelemetryEvent_ClientType" json:"client_type,omitempty"`
	ClientVersion   string                      `protobuf:"bytes,19,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	NodeIdSelf      uint64                      `protobuf:"varint,7,opt,name=node_id_self,json=nodeIdSelf,proto3" json:"node_id_self,omitempty"`
	NodeIdRemote    uint64                      `protobuf:"varint,8,opt,name=node_id_remote,json=nodeIdRemote,proto3" json:"node_id_remote,omitempty"`
	P2PEndpoint     *TelemetryEvent_P2PEndpoint `protobuf:"bytes,9,opt,name=p2p_endpoint,json=p2pEndpoint,proto3" json:"p2p_endpoint,omitempty"`
	HomeDerp        int32                       `protobuf:"varint,10,opt,name=home_derp,json=homeDerp,proto3" json:"home_derp,omitempty"`
	DerpMap         *DERPMap                    `protobuf:"bytes,11,opt,name=derp_map,json=derpMap,proto3" json:"derp_map,omitempty"`
	LatestNetcheck  *Netcheck                   `protobuf:"bytes,12,opt,name=latest_netcheck,json=latestNetcheck,proto3" json:"latest_netcheck,omitempty"`
	ConnectionAge   *durationpb.Duration        `protobuf:"bytes,13,opt,name=connection_age,json=connectionAge,proto3" json:"connection_age,omitempty"`
	ConnectionSetup *durationpb.Duration        `protobuf:"bytes,14,opt,name=connection_setup,json=connectionSetup,proto3" json:"connection_setup,omitempty"`
	P2PSetup        *durationpb.Duration        `protobuf:"bytes,15,opt,name=p2p_setup,json=p2pSetup,proto3" json:"p2p_setup,omitempty"`
	DerpLatency     *durationpb.Duration        `protobuf:"bytes,16,opt,name=derp_latency,json=derpLatency,proto3" json:"derp_latency,omitempty"`
	P2PLatency      *durationpb.Duration        `protobuf:"bytes,17,opt,name=p2p_latency,json=p2pLatency,proto3" json:"p2p_latency,omitempty"`
	ThroughputMbits *wrapperspb.FloatValue      `protobuf:"bytes,18,opt,name=throughput_mbits,json=throughputMbits,proto3" json:"throughput_mbits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{9}
}

func (x *TelemetryEvent) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TelemetryEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *TelemetryEvent) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *TelemetryEvent) GetStatus() TelemetryEvent_Status {
	if x != nil {
		return x.Status
	}
	return TelemetryEvent_CONNECTED
}

func (x *TelemetryEvent) GetClientType() TelemetryEvent_ClientType {
	if x != nil {
		return x.ClientType
	}
	return TelemetryEvent_CLI
}

func (x *TelemetryEvent) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *TelemetryEvent) GetNodeIdSelf() uint64 {
	if x != nil {
		return x.NodeIdSelf
	}
	return 0
}

func (x *TelemetryEvent) GetNodeIdRemote() uint64 {
	if x != nil {
		return x.NodeIdRemote
	}
	return 0
}

func (x *TelemetryEvent) GetP2PEndpoint() *TelemetryEvent_P2PEndpoint {
	if x != nil {
		return x.P2PEndpoint
	}
	return nil
}

func (x *TelemetryEvent) GetHomeDerp() int32 {
	if x != nil {
		return x.HomeDerp
	}
	return 0
}

func (x *TelemetryEvent) GetDerpMap() *DERPMap {
	if x != nil {
		return x.DerpMap
	}
	return nil
}

func (x *TelemetryEvent) GetLatestNetcheck() *Netcheck {
	if x != nil {
		return x.LatestNetcheck
	}
	return nil
}

func (x *TelemetryEvent) GetConnectionAge() *durationpb.Duration {
	if x != nil {
		return x.ConnectionAge
	}
	return nil
}

func (x *TelemetryEvent) GetConnectionSetup() *durationpb.Duration {
	if x != nil {
		return x.ConnectionSetup
	}
	return nil
}

func (x *TelemetryEvent) GetP2PSetup() *durationpb.Duration {
	if x != nil {
		return x.P2PSetup
	}
	return nil
}

func (x *TelemetryEvent) GetDerpLatency() *durationpb.Duration {
	if x != nil {
		return x.DerpLatency
	}
	return nil
}

func (x *TelemetryEvent) GetP2PLatency() *durationpb.Duration {
	if x != nil {
		return x.P2PLatency
	}
	return nil
}

func (x *TelemetryEvent) GetThroughputMbits() *wrapperspb.FloatValue {
	if x != nil {
		return x.ThroughputMbits
	}
	return nil
}

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TelemetryEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{10}
}

func (x *TelemetryRequest) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{11}
}

type WorkspaceUpdatesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceOwnerId []byte                 `protobuf:"bytes,1,opt,name=workspace_owner_id,json=workspaceOwnerId,proto3" json:"workspace_owner_id,omitempty"` // UUID
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkspaceUpdatesRequest) Reset() {
	*x = WorkspaceUpdatesRequest{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceUpdatesRequest) ProtoMessage() {}

func (x *WorkspaceUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceUpdatesRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{12}
}

func (x *WorkspaceUpdatesRequest) GetWorkspaceOwnerId() []byte {
	if x != nil {
		return x.WorkspaceOwnerId
	}
	return nil
}

type WorkspaceUpdate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UpsertedWorkspaces []*Workspace           `protobuf:"bytes,1,rep,name=upserted_workspaces,json=upsertedWorkspaces,proto3" json:"upserted_workspaces,omitempty"`
	UpsertedAgents     []*Agent               `protobuf:"bytes,2,rep,name=upserted_agents,json=upsertedAgents,proto3" json:"upserted_agents,omitempty"`
	DeletedWorkspaces  []*Workspace           `protobuf:"bytes,3,rep,name=deleted_workspaces,json=deletedWorkspaces,proto3" json:"deleted_workspaces,omitempty"`
	DeletedAgents      []*Agent               `protobuf:"bytes,4,rep,name=deleted_agents,json=deletedAgents,proto3" json:"deleted_agents,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkspaceUpdate) Reset() {
	*x = WorkspaceUpdate{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceUpdate) ProtoMessage() {}

func (x *WorkspaceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceUpdate.ProtoReflect.Descriptor instead.
func (*WorkspaceUpdate) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{13}
}

func (x *WorkspaceUpdate) GetUpsertedWorkspaces() []*Workspace {
	if x != nil {
		return x.UpsertedWorkspaces
	}
	return nil
}

func (x *WorkspaceUpdate) GetUpsertedAgents() []*Agent {
	if x != nil {
		return x.UpsertedAgents
	}
	return nil
}

func (x *WorkspaceUpdate) GetDeletedWorkspaces() []*Workspace {
	if x != nil {
		return x.DeletedWorkspaces
	}
	return nil
}

func (x *WorkspaceUpdate) GetDeletedAgents() []*Agent {
	if x != nil {
		return x.DeletedAgents
	}
	return nil
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        Workspace_Status       `protobuf:"varint,3,opt,name=status,proto3,enum=coder.tailnet.v2.Workspace_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{14}
}

func (x *Workspace) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetStatus() Workspace_Status {
	if x != nil {
		return x.Status
	}
	return Workspace_UNKNOWN
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WorkspaceId   []byte                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{15}
}

func (x *Agent) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetWorkspaceId() []byte {
	if x != nil {
		return x.WorkspaceId
	}
	return nil
}

type DERPMap_HomeParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionScore   map[int64]float64      `protobuf:"bytes,1,rep,name=region_score,json=regionScore,proto3" json:"region_score,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DERPMap_HomeParams) Reset() {
	*x = DERPMap_HomeParams{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DERPMap_HomeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DERPMap_HomeParams) ProtoMessage() {}

func (x *DERPMap_HomeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DERPMap_HomeParams.ProtoReflect.Descriptor instead.
func (*DERPMap_HomeParams) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DERPMap_HomeParams) GetRegionScore() map[int64]float64 {
	if x != nil {
		return x.RegionScore
	}
	return nil
}

type DERPMap_Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      int64                  `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	EmbeddedRelay bool                   `protobuf:"varint,2,opt,name=embedded_relay,json=embeddedRelay,proto3" json:"embedded_relay,omitempty"`
	RegionCode    string                 `protobuf:"bytes,3,opt,name=region_code,json=regionCode,proto3" json:"region_code,omitempty"`
	RegionName    string                 `protobuf:"bytes,4,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	Avoid         bool                   `protobuf:"varint,5,opt,name=avoid,proto3" json:"avoid,omitempty"`
	Nodes         []*DERPMap_Region_Node `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DERPMap_Region) Reset() {
	*x = DERPMap_Region{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DERPMap_Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DERPMap_Region) ProtoMessage() {}

func (x *DERPMap_Region) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DERPMap_Region.ProtoReflect.Descriptor instead.
func (*DERPMap_Region) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DERPMap_Region) GetRegionId() int64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *DERPMap_Region) GetEmbeddedRelay() bool {
	if x != nil {
		return x.EmbeddedRelay
	}
	return false
}

func (x *DERPMap_Region) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *DERPMap_Region) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *DERPMap_Region) GetAvoid() bool {
	if x != nil {
		return x.Avoid
	}
	return false
}

func (x *DERPMap_Region) GetNodes() []*DERPMap_Region_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type DERPMap_Region_Node struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RegionId         int64                  `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	HostName         string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	CertName         string                 `protobuf:"bytes,4,opt,name=cert_name,json=certName,proto3" json:"cert_name,omitempty"`
	Ipv4             string                 `protobuf:"bytes,5,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6             string                 `protobuf:"bytes,6,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	StunPort         int32                  `protobuf:"varint,7,opt,name=stun_port,json=stunPort,proto3" json:"stun_port,omitempty"`
	StunOnly         bool                   `protobuf:"varint,8,opt,name=stun_only,json=stunOnly,proto3" json:"stun_only,omitempty"`
	DerpPort         int32                  `protobuf:"varint,9,opt,name=derp_port,json=derpPort,proto3" json:"derp_port,omitempty"`
	InsecureForTests bool                   `protobuf:"varint,10,opt,name=insecure_for_tests,json=insecureForTests,proto3" json:"insecure_for_tests,omitempty"`
	ForceHttp        bool                   `protobuf:"varint,11,opt,name=force_http,json=forceHttp,proto3" json:"force_http,omitempty"`
	StunTestIp       string                 `protobuf:"bytes,12,opt,name=stun_test_ip,json=stunTestIp,proto3" json:"stun_test_ip,omitempty"`
	CanPort_80       bool                   `protobuf:"varint,13,opt,name=can_port_80,json=canPort80,proto3" json:"can_port_80,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DERPMap_Region_Node) Reset() {
	*x = DERPMap_Region_Node{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DERPMap_Region_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DERPMap_Region_Node) ProtoMessage() {}

func (x *DERPMap_Region_Node) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DERPMap_Region_Node.ProtoReflect.Descriptor instead.
func (*DERPMap_Region_Node) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *DERPMap_Region_Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DERPMap_Region_Node) GetRegionId() int64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *DERPMap_Region_Node) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *DERPMap_Region_Node) GetCertName() string {
	if x != nil {
		return x.CertName
	}
	return ""
}

func (x *DERPMap_Region_Node) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *DERPMap_Region_Node) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *DERPMap_Region_Node) GetStunPort() int32 {
	if x != nil {
		return x.StunPort
	}
	return 0
}

func (x *DERPMap_Region_Node) GetStunOnly() bool {
	if x != nil {
		return x.StunOnly
	}
	return false
}

func (x *DERPMap_Region_Node) GetDerpPort() int32 {
	if x != nil {
		return x.DerpPort
	}
	return 0
}

func (x *DERPMap_Region_Node) GetInsecureForTests() bool {
	if x != nil {
		return x.InsecureForTests
	}
	return false
}

func (x *DERPMap_Region_Node) GetForceHttp() bool {
	if x != nil {
		return x.ForceHttp
	}
	return false
}

func (x *DERPMap_Region_Node) GetStunTestIp() string {
	if x != nil {
		return x.StunTestIp
	}
	return ""
}

func (x *DERPMap_Region_Node) GetCanPort_80() bool {
	if x != nil {
		return x.CanPort_80
	}
	return false
}

type CoordinateRequest_UpdateSelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateRequest_UpdateSelf) Reset() {
	*x = CoordinateRequest_UpdateSelf{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateRequest_UpdateSelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRequest_UpdateSelf) ProtoMessage() {}

func (x *CoordinateRequest_UpdateSelf) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRequest_UpdateSelf.ProtoReflect.Descriptor instead.
func (*CoordinateRequest_UpdateSelf) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CoordinateRequest_UpdateSelf) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type CoordinateRequest_Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateRequest_Disconnect) Reset() {
	*x = CoordinateRequest_Disconnect{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateRequest_Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRequest_Disconnect) ProtoMessage() {}

func (x *CoordinateRequest_Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRequest_Disconnect.ProtoReflect.Descriptor instead.
func (*CoordinateRequest_Disconnect) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{5, 1}
}

type CoordinateRequest_Tunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateRequest_Tunnel) Reset() {
	*x = CoordinateRequest_Tunnel{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateRequest_Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRequest_Tunnel) ProtoMessage() {}

func (x *CoordinateRequest_Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRequest_Tunnel.ProtoReflect.Descriptor instead.
func (*CoordinateRequest_Tunnel) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{5, 2}
}

func (x *CoordinateRequest_Tunnel) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// ReadyForHandskales are sent from destinations back to the source,
// acknowledging receipt of the source's node. If the source starts pinging
// before a ReadyForHandshake, the Wireguard handshake will likely be
// dropped.
type CoordinateRequest_ReadyForHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateRequest_ReadyForHandshake) Reset() {
	*x = CoordinateRequest_ReadyForHandshake{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateRequest_ReadyForHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRequest_ReadyForHandshake) ProtoMessage() {}

func (x *CoordinateRequest_ReadyForHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRequest_ReadyForHandshake.ProtoReflect.Descriptor instead.
func (*CoordinateRequest_ReadyForHandshake) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{5, 3}
}

func (x *CoordinateRequest_ReadyForHandshake) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type CoordinateResponse_PeerUpdate struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Id            []byte                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Node          *Node                              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Kind          CoordinateResponse_PeerUpdate_Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=coder.tailnet.v2.CoordinateResponse_PeerUpdate_Kind" json:"kind,omitempty"`
	Reason        string                             `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateResponse_PeerUpdate) Reset() {
	*x = CoordinateResponse_PeerUpdate{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateResponse_PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateResponse_PeerUpdate) ProtoMessage() {}

func (x *CoordinateResponse_PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateResponse_PeerUpdate.ProtoReflect.Descriptor instead.
func (*CoordinateResponse_PeerUpdate) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CoordinateResponse_PeerUpdate) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CoordinateResponse_PeerUpdate) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *CoordinateResponse_PeerUpdate) GetKind() CoordinateResponse_PeerUpdate_Kind {
	if x != nil {
		return x.Kind
	}
	return CoordinateResponse_PeerUpdate_KIND_UNSPECIFIED
}

func (x *CoordinateResponse_PeerUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Netcheck_NetcheckIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Fields        *IPFields              `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Netcheck_NetcheckIP) Reset() {
	*x = Netcheck_NetcheckIP{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Netcheck_NetcheckIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Netcheck_NetcheckIP) ProtoMessage() {}

func (x *Netcheck_NetcheckIP) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Netcheck_NetcheckIP.ProtoReflect.Descriptor instead.
func (*Netcheck_NetcheckIP) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{8, 2}
}

func (x *Netcheck_NetcheckIP) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Netcheck_NetcheckIP) GetFields() *IPFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type TelemetryEvent_P2PEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Fields        *IPFields              `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent_P2PEndpoint) Reset() {
	*x = TelemetryEvent_P2PEndpoint{}
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent_P2PEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent_P2PEndpoint) ProtoMessage() {}

func (x *TelemetryEvent_P2PEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_tailnet_proto_tailnet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent_P2PEndpoint.ProtoReflect.Descriptor instead.
func (*TelemetryEvent_P2PEndpoint) Descriptor() ([]byte, []int) {
	return file_tailnet_proto_tailnet_proto_rawDescGZIP(), []int{9, 0}
}

func (x *TelemetryEvent_P2PEndpoint) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TelemetryEvent_P2PEndpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TelemetryEvent_P2PEndpoint) GetFields() *IPFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_tailnet_proto_tailnet_proto protoreflect.FileDescriptor

const file_tailnet_proto_tailnet_proto_rawDesc = "" +
	"\n" +
	"\x1btailnet/proto/tailnet.proto\x12\x10coder.tailnet.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xff\a\n" +
	"\aDERPMap\x12E\n" +
	"\vhome_params\x18\x01 \x01(\v2$.coder.tailnet.v2.DERPMap.HomeParamsR\n" +
	"homeParams\x12@\n" +
	"\aregions\x18\x02 \x03(\v2&.coder.tailnet.v2.DERPMap.RegionsEntryR\aregions\x1a\xa6\x01\n" +
	"\n" +
	"HomeParams\x12X\n" +
	"\fregion_score\x18\x01 \x03(\v25.coder.tailnet.v2.DERPMap.HomeParams.RegionScoreEntryR\vregionScore\x1a>\n" +
	"\x10RegionScoreEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a\xe3\x04\n" +
	"\x06Region\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x03R\bregionId\x12%\n" +
	"\x0eembedded_relay\x18\x02 \x01(\bR\rembeddedRelay\x12\x1f\n" +
	"\vregion_code\x18\x03 \x01(\tR\n" +
	"regionCode\x12\x1f\n" +
	"\vregion_name\x18\x04 \x01(\tR\n" +
	"regionName\x12\x14\n" +
	"\x05avoid\x18\x05 \x01(\bR\x05avoid\x12;\n" +
	"\x05nodes\x18\x06 \x03(\v2%.coder.tailnet.v2.DERPMap.Region.NodeR\x05nodes\x1a\xff\x02\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\x03R\bregionId\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\x12\x1b\n" +
	"\tcert_name\x18\x04 \x01(\tR\bcertName\x12\x12\n" +
	"\x04ipv4\x18\x05 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x06 \x01(\tR\x04ipv6\x12\x1b\n" +
	"\tstun_port\x18\a \x01(\x05R\bstunPort\x12\x1b\n" +
	"\tstun_only\x18\b \x01(\bR\bstunOnly\x12\x1b\n" +
	"\tderp_port\x18\t \x01(\x05R\bderpPort\x12,\n" +
	"\x12insecure_for_tests\x18\n" +
	" \x01(\bR\x10insecureForTests\x12\x1d\n" +
	"\n" +
	"force_http\x18\v \x01(\bR\tforceHttp\x12 \n" +
	"\fstun_test_ip\x18\f \x01(\tR\n" +
	"stunTestIp\x12\x1e\n" +
	"\vcan_port_80\x18\r \x01(\bR\tcanPort80\x1a\\\n" +
	"\fRegionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .coder.tailnet.v2.DERPMap.RegionR\x05value:\x028\x01\"\x17\n" +
	"\x15StreamDERPMapsRequest\"\x85\x05\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12/\n" +
	"\x05as_of\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05disco\x18\x04 \x01(\tR\x05disco\x12%\n" +
	"\x0epreferred_derp\x18\x05 \x01(\x05R\rpreferredDerp\x12J\n" +
	"\fderp_latency\x18\x06 \x03(\v2'.coder.tailnet.v2.Node.DerpLatencyEntryR\vderpLatency\x12c\n" +
	"\x15derp_forced_websocket\x18\a \x03(\v2/.coder.tailnet.v2.Node.DerpForcedWebsocketEntryR\x13derpForcedWebsocket\x12\x1c\n" +
	"\taddresses\x18\b \x03(\tR\taddresses\x12\x1f\n" +
	"\vallowed_ips\x18\t \x03(\tR\n" +
	"allowedIps\x12\x1c\n" +
	"\tendpoints\x18\n" +
	" \x03(\tR\tendpoints\x12+\n" +
	"\x11short_description\x18\v \x01(\tR\x10shortDescription\x12\x1a\n" +
	"\bhostname\x18\f \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\r \x01(\tR\x02os\x1a>\n" +
	"\x10DerpLatencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aF\n" +
	"\x18DerpForcedWebsocketEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1b\n" +
	"\x19RefreshResumeTokenRequest\"\xc0\x01\n" +
	"\x1aRefreshResumeTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x128\n" +
	"\n" +
	"refresh_in\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\trefreshIn\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\fR\x06peerId\"\xbe\x04\n" +
	"\x11CoordinateRequest\x12O\n" +
	"\vupdate_self\x18\x01 \x01(\v2..coder.tailnet.v2.CoordinateRequest.UpdateSelfR\n" +
	"updateSelf\x12N\n" +
	"\n" +
	"disconnect\x18\x02 \x01(\v2..coder.tailnet.v2.CoordinateRequest.DisconnectR\n" +
	"disconnect\x12I\n" +
	"\n" +
	"add_tunnel\x18\x03 \x01(\v2*.coder.tailnet.v2.CoordinateRequest.TunnelR\taddTunnel\x12O\n" +
	"\rremove_tunnel\x18\x04 \x01(\v2*.coder.tailnet.v2.CoordinateRequest.TunnelR\fremoveTunnel\x12e\n" +
	"\x13ready_for_handshake\x18\x05 \x03(\v25.coder.tailnet.v2.CoordinateRequest.ReadyForHandshakeR\x11readyForHandshake\x1a8\n" +
	"\n" +
	"UpdateSelf\x12*\n" +
	"\x04node\x18\x01 \x01(\v2\x16.coder.tailnet.v2.NodeR\x04node\x1a\f\n" +
	"\n" +
	"Disconnect\x1a\x18\n" +
	"\x06Tunnel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x1a#\n" +
	"\x11ReadyForHandshake\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\x88\x03\n" +
	"\x12CoordinateResponse\x12R\n" +
	"\fpeer_updates\x18\x01 \x03(\v2/.coder.tailnet.v2.CoordinateResponse.PeerUpdateR\vpeerUpdates\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a\x87\x02\n" +
	"\n" +
	"PeerUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12*\n" +
	"\x04node\x18\x02 \x01(\v2\x16.coder.tailnet.v2.NodeR\x04node\x12H\n" +
	"\x04kind\x18\x03 \x01(\x0e24.coder.tailnet.v2.CoordinateResponse.PeerUpdate.KindR\x04kind\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"[\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NODE\x10\x01\x12\x10\n" +
	"\fDISCONNECTED\x10\x02\x12\b\n" +
	"\x04LOST\x10\x03\x12\x17\n" +
	"\x13READY_FOR_HANDSHAKE\x10\x04\"\xa0\x01\n" +
	"\bIPFields\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x128\n" +
	"\x05class\x18\x02 \x01(\x0e2\".coder.tailnet.v2.IPFields.IPClassR\x05class\"@\n" +
	"\aIPClass\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x00\x12\v\n" +
	"\aPRIVATE\x10\x01\x12\x0e\n" +
	"\n" +
	"LINK_LOCAL\x10\x02\x12\f\n" +
	"\bLOOPBACK\x10\x03\"\xec\b\n" +
	"\bNetcheck\x12\x10\n" +
	"\x03UDP\x18\x01 \x01(\bR\x03UDP\x12\x12\n" +
	"\x04IPv6\x18\x02 \x01(\bR\x04IPv6\x12\x12\n" +
	"\x04IPv4\x18\x03 \x01(\bR\x04IPv4\x12 \n" +
	"\vIPv6CanSend\x18\x04 \x01(\bR\vIPv6CanSend\x12 \n" +
	"\vIPv4CanSend\x18\x05 \x01(\bR\vIPv4CanSend\x12\x16\n" +
	"\x06ICMPv4\x18\x06 \x01(\bR\x06ICMPv4\x128\n" +
	"\tOSHasIPv6\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\tOSHasIPv6\x12P\n" +
	"\x15MappingVariesByDestIP\x18\b \x01(\v2\x1a.google.protobuf.BoolValueR\x15MappingVariesByDestIP\x12<\n" +
	"\vHairPinning\x18\t \x01(\v2\x1a.google.protobuf.BoolValueR\vHairPinning\x12.\n" +
	"\x04UPnP\x18\n" +
	" \x01(\v2\x1a.google.protobuf.BoolValueR\x04UPnP\x12,\n" +
	"\x03PMP\x18\v \x01(\v2\x1a.google.protobuf.BoolValueR\x03PMP\x12,\n" +
	"\x03PCP\x18\f \x01(\v2\x1a.google.protobuf.BoolValueR\x03PCP\x12$\n" +
	"\rPreferredDERP\x18\r \x01(\x03R\rPreferredDERP\x12Y\n" +
	"\x0fRegionV4Latency\x18\x0e \x03(\v2/.coder.tailnet.v2.Netcheck.RegionV4LatencyEntryR\x0fRegionV4Latency\x12Y\n" +
	"\x0fRegionV6Latency\x18\x0f \x03(\v2/.coder.tailnet.v2.Netcheck.RegionV6LatencyEntryR\x0fRegionV6Latency\x12A\n" +
	"\bGlobalV4\x18\x11 \x01(\v2%.coder.tailnet.v2.Netcheck.NetcheckIPR\bGlobalV4\x12A\n" +
	"\bGlobalV6\x18\x12 \x01(\v2%.coder.tailnet.v2.Netcheck.NetcheckIPR\bGlobalV6\x1a]\n" +
	"\x14RegionV4LatencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01\x1a]\n" +
	"\x14RegionV6LatencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01\x1aT\n" +
	"\n" +
	"NetcheckIP\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x122\n" +
	"\x06fields\x18\x02 \x01(\v2\x1a.coder.tailnet.v2.IPFieldsR\x06fields\"\xb2\t\n" +
	"\x0eTelemetryEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12 \n" +
	"\vapplication\x18\x03 \x01(\tR\vapplication\x12?\n" +
	"\x06status\x18\x04 \x01(\x0e2'.coder.tailnet.v2.TelemetryEvent.StatusR\x06status\x12L\n" +
	"\vclient_type\x18\x06 \x01(\x0e2+.coder.tailnet.v2.TelemetryEvent.ClientTypeR\n" +
	"clientType\x12%\n" +
	"\x0eclient_version\x18\x13 \x01(\tR\rclientVersion\x12 \n" +
	"\fnode_id_self\x18\a \x01(\x04R\n" +
	"nodeIdSelf\x12$\n" +
	"\x0enode_id_remote\x18\b \x01(\x04R\fnodeIdRemote\x12O\n" +
	"\fp2p_endpoint\x18\t \x01(\v2,.coder.tailnet.v2.TelemetryEvent.P2PEndpointR\vp2pEndpoint\x12\x1b\n" +
	"\thome_derp\x18\n" +
	" \x01(\x05R\bhomeDerp\x124\n" +
	"\bderp_map\x18\v \x01(\v2\x19.coder.tailnet.v2.DERPMapR\aderpMap\x12C\n" +
	"\x0flatest_netcheck\x18\f \x01(\v2\x1a.coder.tailnet.v2.NetcheckR\x0elatestNetcheck\x12@\n" +
	"\x0econnection_age\x18\r \x01(\v2\x19.google.protobuf.DurationR\rconnectionAge\x12D\n" +
	"\x10connection_setup\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\x0fconnectionSetup\x126\n" +
	"\tp2p_setup\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\bp2pSetup\x12<\n" +
	"\fderp_latency\x18\x10 \x01(\v2\x19.google.protobuf.DurationR\vderpLatency\x12:\n" +
	"\vp2p_latency\x18\x11 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"p2pLatency\x12F\n" +
	"\x10throughput_mbits\x18\x12 \x01(\v2\x1b.google.protobuf.FloatValueR\x0fthroughputMbits\x1ai\n" +
	"\vP2PEndpoint\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x122\n" +
	"\x06fields\x18\x03 \x01(\v2\x1a.coder.tailnet.v2.IPFieldsR\x06fields\")\n" +
	"\x06Status\x12\r\n" +
	"\tCONNECTED\x10\x00\x12\x10\n" +
	"\fDISCONNECTED\x10\x01\"9\n" +
	"\n" +
	"ClientType\x12\a\n" +
	"\x03CLI\x10\x00\x12\t\n" +
	"\x05AGENT\x10\x01\x12\n" +
	"\n" +
	"\x06CODERD\x10\x02\x12\v\n" +
	"\aWSPROXY\x10\x03J\x04\b\x05\x10\x06\"L\n" +
	"\x10TelemetryRequest\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .coder.tailnet.v2.TelemetryEventR\x06events\"\x13\n" +
	"\x11TelemetryResponse\"G\n" +
	"\x17WorkspaceUpdatesRequest\x12,\n" +
	"\x12workspace_owner_id\x18\x01 \x01(\fR\x10workspaceOwnerId\"\xad\x02\n" +
	"\x0fWorkspaceUpdate\x12L\n" +
	"\x13upserted_workspaces\x18\x01 \x03(\v2\x1b.coder.tailnet.v2.WorkspaceR\x12upsertedWorkspaces\x12@\n" +
	"\x0fupserted_agents\x18\x02 \x03(\v2\x17.coder.tailnet.v2.AgentR\x0eupsertedAgents\x12J\n" +
	"\x12deleted_workspaces\x18\x03 \x03(\v2\x1b.coder.tailnet.v2.WorkspaceR\x11deletedWorkspaces\x12>\n" +
	"\x0edeleted_agents\x18\x04 \x03(\v2\x17.coder.tailnet.v2.AgentR\rdeletedAgents\"\x8a\x02\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".coder.tailnet.v2.Workspace.StatusR\x06status\"\x9c\x01\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bSTARTING\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\f\n" +
	"\bSTOPPING\x10\x04\x12\v\n" +
	"\aSTOPPED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06\x12\r\n" +
	"\tCANCELING\x10\a\x12\f\n" +
	"\bCANCELED\x10\b\x12\f\n" +
	"\bDELETING\x10\t\x12\v\n" +
	"\aDELETED\x10\n" +
	"\"N\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\fR\vworkspaceId2\xed\x03\n" +
	"\aTailnet\x12X\n" +
	"\rPostTelemetry\x12\".coder.tailnet.v2.TelemetryRequest\x1a#.coder.tailnet.v2.TelemetryResponse\x12V\n" +
	"\x0eStreamDERPMaps\x12'.coder.tailnet.v2.StreamDERPMapsRequest\x1a\x19.coder.tailnet.v2.DERPMap0\x01\x12o\n" +
	"\x12RefreshResumeToken\x12+.coder.tailnet.v2.RefreshResumeTokenRequest\x1a,.coder.tailnet.v2.RefreshResumeTokenResponse\x12[\n" +
	"\n" +
	"Coordinate\x12#.coder.tailnet.v2.CoordinateRequest\x1a$.coder.tailnet.v2.CoordinateResponse(\x010\x01\x12b\n" +
	"\x10WorkspaceUpdates\x12).coder.tailnet.v2.WorkspaceUpdatesRequest\x1a!.coder.tailnet.v2.WorkspaceUpdate0\x01B)Z'github.com/coder/coder/v2/tailnet/protob\x06proto3"

var (
	file_tailnet_proto_tailnet_proto_rawDescOnce sync.Once
	file_tailnet_proto_tailnet_proto_rawDescData []byte
)

func file_tailnet_proto_tailnet_proto_rawDescGZIP() []byte {
	file_tailnet_proto_tailnet_proto_rawDescOnce.Do(func() {
		file_tailnet_proto_tailnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tailnet_proto_tailnet_proto_rawDesc), len(file_tailnet_proto_tailnet_proto_rawDesc)))
	})
	return file_tailnet_proto_tailnet_proto_rawDescData
}

var file_tailnet_proto_tailnet_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_tailnet_proto_tailnet_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_tailnet_proto_tailnet_proto_goTypes = []any{
	(CoordinateResponse_PeerUpdate_Kind)(0),     // 0: coder.tailnet.v2.CoordinateResponse.PeerUpdate.Kind
	(IPFields_IPClass)(0),                       // 1: coder.tailnet.v2.IPFields.IPClass
	(TelemetryEvent_Status)(0),                  // 2: coder.tailnet.v2.TelemetryEvent.Status
	(TelemetryEvent_ClientType)(0),              // 3: coder.tailnet.v2.TelemetryEvent.ClientType
	(Workspace_Status)(0),                       // 4: coder.tailnet.v2.Workspace.Status
	(*DERPMap)(nil),                             // 5: coder.tailnet.v2.DERPMap
	(*StreamDERPMapsRequest)(nil),               // 6: coder.tailnet.v2.StreamDERPMapsRequest
	(*Node)(nil),                                // 7: coder.tailnet.v2.Node
	(*RefreshResumeTokenRequest)(nil),           // 8: coder.tailnet.v2.RefreshResumeTokenRequest
	(*RefreshResumeTokenResponse)(nil),          // 9: coder.tailnet.v2.RefreshResumeTokenResponse
	(*CoordinateRequest)(nil),                   // 10: coder.tailnet.v2.CoordinateRequest
	(*CoordinateResponse)(nil),                  // 11: coder.tailnet.v2.CoordinateResponse
	(*IPFields)(nil),                            // 12: coder.tailnet.v2.IPFields
	(*Netcheck)(nil),                            // 13: coder.tailnet.v2.Netcheck
	(*TelemetryEvent)(nil),                      // 14: coder.tailnet.v2.TelemetryEvent
	(*TelemetryRequest)(nil),                    // 15: coder.tailnet.v2.TelemetryRequest
	(*TelemetryResponse)(nil),                   // 16: coder.tailnet.v2.TelemetryResponse
	(*WorkspaceUpdatesRequest)(nil),             // 17: coder.tailnet.v2.WorkspaceUpdatesRequest
	(*WorkspaceUpdate)(nil),                     // 18: coder.tailnet.v2.WorkspaceUpdate
	(*Workspace)(nil),                           // 19: coder.tailnet.v2.Workspace
	(*Agent)(nil),                               // 20: coder.tailnet.v2.Agent
	(*DERPMap_HomeParams)(nil),                  // 21: coder.tailnet.v2.DERPMap.HomeParams
	(*DERPMap_Region)(nil),                      // 22: coder.tailnet.v2.DERPMap.Region
	nil,                                         // 23: coder.tailnet.v2.DERPMap.RegionsEntry
	nil,                                         // 24: coder.tailnet.v2.DERPMap.HomeParams.RegionScoreEntry
	(*DERPMap_Region_Node)(nil),                 // 25: coder.tailnet.v2.DERPMap.Region.Node
	nil,                                         // 26: coder.tailnet.v2.Node.DerpLatencyEntry
	nil,                                         // 27: coder.tailnet.v2.Node.DerpForcedWebsocketEntry
	(*CoordinateRequest_UpdateSelf)(nil),        // 28: coder.tailnet.v2.CoordinateRequest.UpdateSelf
	(*CoordinateRequest_Disconnect)(nil),        // 29: coder.tailnet.v2.CoordinateRequest.Disconnect
	(*CoordinateRequest_Tunnel)(nil),            // 30: coder.tailnet.v2.CoordinateRequest.Tunnel
	(*CoordinateRequest_ReadyForHandshake)(nil), // 31: coder.tailnet.v2.CoordinateRequest.ReadyForHandshake
	(*CoordinateResponse_PeerUpdate)(nil),       // 32: coder.tailnet.v2.CoordinateResponse.PeerUpdate
	nil,                                         // 33: coder.tailnet.v2.Netcheck.RegionV4LatencyEntry
	nil,                                         // 34: coder.tailnet.v2.Netcheck.RegionV6LatencyEntry
	(*Netcheck_NetcheckIP)(nil),                 // 35: coder.tailnet.v2.Netcheck.NetcheckIP
	(*TelemetryEvent_P2PEndpoint)(nil),          // 36: coder.tailnet.v2.TelemetryEvent.P2PEndpoint
	(*timestamppb.Timestamp)(nil),               // 37: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                 // 38: google.protobuf.Duration
	(*wrapperspb.BoolValue)(nil),                // 39: google.protobuf.BoolValue
	(*wrapperspb.FloatValue)(nil),               // 40: google.protobuf.FloatValue
}
var file_tailnet_proto_tailnet_proto_depIdxs = []int32{
	21, // 0: coder.tailnet.v2.DERPMap.home_params:type_name -> coder.tailnet.v2.DERPMap.HomeParams
	23, // 1: coder.tailnet.v2.DERPMap.regions:type_name -> coder.tailnet.v2.DERPMap.RegionsEntry
	37, // 2: coder.tailnet.v2.Node.as_of:type_name -> google.protobuf.Timestamp
	26, // 3: coder.tailnet.v2.Node.derp_latency:type_name -> coder.tailnet.v2.Node.DerpLatencyEntry
	27, // 4: coder.tailnet.v2.Node.derp_forced_websocket:type_name -> coder.tailnet.v2.Node.DerpForcedWebsocketEntry
	38, // 5: coder.tailnet.v2.RefreshResumeTokenResponse.refresh_in:type_name -> google.protobuf.Duration
	37, // 6: coder.tailnet.v2.RefreshResumeTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	28, // 7: coder.tailnet.v2.CoordinateRequest.update_self:type_name -> coder.tailnet.v2.CoordinateRequest.UpdateSelf
	29, // 8: coder.tailnet.v2.CoordinateRequest.disconnect:type_name -> coder.tailnet.v2.CoordinateRequest.Disconnect
	30, // 9: coder.tailnet.v2.CoordinateRequest.add_tunnel:type_name -> coder.tailnet.v2.CoordinateRequest.Tunnel
	30, // 10: coder.tailnet.v2.CoordinateRequest.remove_tunnel:type_name -> coder.tailnet.v2.CoordinateRequest.Tunnel
	31, // 11: coder.tailnet.v2.CoordinateRequest.ready_for_handshake:type_name -> coder.tailnet.v2.CoordinateRequest.ReadyForHandshake
	32, // 12: coder.tailnet.v2.CoordinateResponse.peer_updates:type_name -> coder.tailnet.v2.CoordinateResponse.PeerUpdate
	1,  // 13: coder.tailnet.v2.IPFields.class:type_name -> coder.tailnet.v2.IPFields.IPClass
	39, // 14: coder.tailnet.v2.Netcheck.OSHasIPv6:type_name -> google.protobuf.BoolValue
	39, // 15: coder.tailnet.v2.Netcheck.MappingVariesByDestIP:type_name -> google.protobuf.BoolValue
	39, // 16: coder.tailnet.v2.Netcheck.HairPinning:type_name -> google.protobuf.BoolValue
	39, // 17: coder.tailnet.v2.Netcheck.UPnP:type_name -> google.protobuf.BoolValue
	39, // 18: coder.tailnet.v2.Netcheck.PMP:type_name -> google.protobuf.BoolValue
	39, // 19: coder.tailnet.v2.Netcheck.PCP:type_name -> google.protobuf.BoolValue
	33, // 20: coder.tailnet.v2.Netcheck.RegionV4Latency:type_name -> coder.tailnet.v2.Netcheck.RegionV4LatencyEntry
	34, // 21: coder.tailnet.v2.Netcheck.RegionV6Latency:type_name -> coder.tailnet.v2.Netcheck.RegionV6LatencyEntry
	35, // 22: coder.tailnet.v2.Netcheck.GlobalV4:type_name -> coder.tailnet.v2.Netcheck.NetcheckIP
	35, // 23: coder.tailnet.v2.Netcheck.GlobalV6:type_name -> coder.tailnet.v2.Netcheck.NetcheckIP
	37, // 24: coder.tailnet.v2.TelemetryEvent.time:type_name -> google.protobuf.Timestamp
	2,  // 25: coder.tailnet.v2.TelemetryEvent.status:type_name -> coder.tailnet.v2.TelemetryEvent.Status
	3,  // 26: coder.tailnet.v2.TelemetryEvent.client_type:type_name -> coder.tailnet.v2.TelemetryEvent.ClientType
	36, // 27: coder.tailnet.v2.TelemetryEvent.p2p_endpoint:type_name -> coder.tailnet.v2.TelemetryEvent.P2PEndpoint
	5,  // 28: coder.tailnet.v2.TelemetryEvent.derp_map:type_name -> coder.tailnet.v2.DERPMap
	13, // 29: coder.tailnet.v2.TelemetryEvent.latest_netcheck:type_name -> coder.tailnet.v2.Netcheck
	38, // 30: coder.tailnet.v2.TelemetryEvent.connection_age:type_name -> google.protobuf.Duration
	38, // 31: coder.tailnet.v2.TelemetryEvent.connection_setup:type_name -> google.protobuf.Duration
	38, // 32: coder.tailnet.v2.TelemetryEvent.p2p_setup:type_name -> google.protobuf.Duration
	38, // 33: coder.tailnet.v2.TelemetryEvent.derp_latency:type_name -> google.protobuf.Duration
	38, // 34: coder.tailnet.v2.TelemetryEvent.p2p_latency:type_name -> google.protobuf.Duration
	40, // 35: coder.tailnet.v2.TelemetryEvent.throughput_mbits:type_name -> google.protobuf.FloatValue
	14, // 36: coder.tailnet.v2.TelemetryRequest.events:type_name -> coder.tailnet.v2.TelemetryEvent
	19, // 37: coder.tailnet.v2.WorkspaceUpdate.upserted_workspaces:type_name -> coder.tailnet.v2.Workspace
	20, // 38: coder.tailnet.v2.WorkspaceUpdate.upserted_agents:type_name -> coder.tailnet.v2.Agent
	19, // 39: coder.tailnet.v2.WorkspaceUpdate.deleted_workspaces:type_name -> coder.tailnet.v2.Workspace
	20, // 40: coder.tailnet.v2.WorkspaceUpdate.deleted_agents:type_name -> coder.tailnet.v2.Agent
	4,  // 41: coder.tailnet.v2.Workspace.status:type_name -> coder.tailnet.v2.Workspace.Status
	24, // 42: coder.tailnet.v2.DERPMap.HomeParams.region_score:type_name -> coder.tailnet.v2.DERPMap.HomeParams.RegionScoreEntry
	25, // 43: coder.tailnet.v2.DERPMap.Region.nodes:type_name -> coder.tailnet.v2.DERPMap.Region.Node
	22, // 44: coder.tailnet.v2.DERPMap.RegionsEntry.value:type_name -> coder.tailnet.v2.DERPMap.Region
	7,  // 45: coder.tailnet.v2.CoordinateRequest.UpdateSelf.node:type_name -> coder.tailnet.v2.Node
	7,  // 46: coder.tailnet.v2.CoordinateResponse.PeerUpdate.node:type_name -> coder.tailnet.v2.Node
	0,  // 47: coder.tailnet.v2.CoordinateResponse.PeerUpdate.kind:type_name -> coder.tailnet.v2.CoordinateResponse.PeerUpdate.Kind
	38, // 48: coder.tailnet.v2.Netcheck.RegionV4LatencyEntry.value:type_name -> google.protobuf.Duration
	38, // 49: coder.tailnet.v2.Netcheck.RegionV6LatencyEntry.value:type_name -> google.protobuf.Duration
	12, // 50: coder.tailnet.v2.Netcheck.NetcheckIP.fields:type_name -> coder.tailnet.v2.IPFields
	12, // 51: coder.tailnet.v2.TelemetryEvent.P2PEndpoint.fields:type_name -> coder.tailnet.v2.IPFields
	15, // 52: coder.tailnet.v2.Tailnet.PostTelemetry:input_type -> coder.tailnet.v2.TelemetryRequest
	6,  // 53: coder.tailnet.v2.Tailnet.StreamDERPMaps:input_type -> coder.tailnet.v2.StreamDERPMapsRequest
	8,  // 54: coder.tailnet.v2.Tailnet.RefreshResumeToken:input_type -> coder.tailnet.v2.RefreshResumeTokenRequest
	10, // 55: coder.tailnet.v2.Tailnet.Coordinate:input_type -> coder.tailnet.v2.CoordinateRequest
	17, // 56: coder.tailnet.v2.Tailnet.WorkspaceUpdates:input_type -> coder.tailnet.v2.WorkspaceUpdatesRequest
	16, // 57: coder.tailnet.v2.Tailnet.PostTelemetry:output_type -> coder.tailnet.v2.TelemetryResponse
	5,  // 58: coder.tailnet.v2.Tailnet.StreamDERPMaps:output_type -> coder.tailnet.v2.DERPMap
	9,  // 59: coder.tailnet.v2.Tailnet.RefreshResumeToken:output_type -> coder.tailnet.v2.RefreshResumeTokenResponse
	11, // 60: coder.tailnet.v2.Tailnet.Coordinate:output_type -> coder.tailnet.v2.CoordinateResponse
	18, // 61: coder.tailnet.v2.Tailnet.WorkspaceUpdates:output_type -> coder.tailnet.v2.WorkspaceUpdate
	57, // [57:62] is the sub-list for method output_type
	52, // [52:57] is the sub-list for method input_type
	52, // [52:52] is the sub-list for extension type_name
	52, // [52:52] is the sub-list for extension extendee
	0,  // [0:52] is the sub-list for field type_name
}

func init() { file_tailnet_proto_tailnet_proto_init() }
func file_tailnet_proto_tailnet_proto_init() {
	if File_tailnet_proto_tailnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tailnet_proto_tailnet_proto_rawDesc), len(file_tailnet_proto_tailnet_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tailnet_proto_tailnet_proto_goTypes,
		DependencyIndexes: file_tailnet_proto_tailnet_proto_depIdxs,
		EnumInfos:         file_tailnet_proto_tailnet_proto_enumTypes,
		MessageInfos:      file_tailnet_proto_tailnet_proto_msgTypes,
	}.Build()
	File_tailnet_proto_tailnet_proto = out.File
	file_tailnet_proto_tailnet_proto_goTypes = nil
	file_tailnet_proto_tailnet_proto_depIdxs = nil
}
