// Code generated by scripts/apikeyscopesgen. DO NOT EDIT.
package codersdk

const (
	// Deprecated: use codersdk.APIKeyScopeCoderAll instead.
	APIKeyScopeAll APIKeyScope = "all"
	// Deprecated: use codersdk.APIKeyScopeCoderApplicationConnect instead.
	APIKeyScopeApplicationConnect          APIKeyScope = "application_connect"
	APIKeyScopeApiKeyAll                   APIKeyScope = "api_key:*"
	APIKeyScopeApiKeyCreate                APIKeyScope = "api_key:create"
	APIKeyScopeApiKeyDelete                APIKeyScope = "api_key:delete"
	APIKeyScopeApiKeyRead                  APIKeyScope = "api_key:read"
	APIKeyScopeApiKeyUpdate                APIKeyScope = "api_key:update"
	APIKeyScopeCoderAll                    APIKeyScope = "coder:all"
	APIKeyScopeCoderApplicationConnect     APIKeyScope = "coder:application_connect"
	APIKeyScopeFileAll                     APIKeyScope = "file:*"
	APIKeyScopeFileCreate                  APIKeyScope = "file:create"
	APIKeyScopeFileRead                    APIKeyScope = "file:read"
	APIKeyScopeTemplateAll                 APIKeyScope = "template:*"
	APIKeyScopeTemplateCreate              APIKeyScope = "template:create"
	APIKeyScopeTemplateDelete              APIKeyScope = "template:delete"
	APIKeyScopeTemplateRead                APIKeyScope = "template:read"
	APIKeyScopeTemplateUpdate              APIKeyScope = "template:update"
	APIKeyScopeTemplateUse                 APIKeyScope = "template:use"
	APIKeyScopeUserReadPersonal            APIKeyScope = "user:read_personal"
	APIKeyScopeUserUpdatePersonal          APIKeyScope = "user:update_personal"
	APIKeyScopeUserSecretAll               APIKeyScope = "user_secret:*"
	APIKeyScopeUserSecretCreate            APIKeyScope = "user_secret:create"
	APIKeyScopeUserSecretDelete            APIKeyScope = "user_secret:delete"
	APIKeyScopeUserSecretRead              APIKeyScope = "user_secret:read"
	APIKeyScopeUserSecretUpdate            APIKeyScope = "user_secret:update"
	APIKeyScopeWorkspaceAll                APIKeyScope = "workspace:*"
	APIKeyScopeWorkspaceApplicationConnect APIKeyScope = "workspace:application_connect"
	APIKeyScopeWorkspaceCreate             APIKeyScope = "workspace:create"
	APIKeyScopeWorkspaceDelete             APIKeyScope = "workspace:delete"
	APIKeyScopeWorkspaceRead               APIKeyScope = "workspace:read"
	APIKeyScopeWorkspaceSsh                APIKeyScope = "workspace:ssh"
	APIKeyScopeWorkspaceStart              APIKeyScope = "workspace:start"
	APIKeyScopeWorkspaceStop               APIKeyScope = "workspace:stop"
	APIKeyScopeWorkspaceUpdate             APIKeyScope = "workspace:update"
)

// PublicAPIKeyScopes lists all public low-level API key scopes.
var PublicAPIKeyScopes = []APIKeyScope{
	APIKeyScopeApiKeyAll,
	APIKeyScopeApiKeyCreate,
	APIKeyScopeApiKeyDelete,
	APIKeyScopeApiKeyRead,
	APIKeyScopeApiKeyUpdate,
	APIKeyScopeCoderAll,
	APIKeyScopeCoderApplicationConnect,
	APIKeyScopeFileAll,
	APIKeyScopeFileCreate,
	APIKeyScopeFileRead,
	APIKeyScopeTemplateAll,
	APIKeyScopeTemplateCreate,
	APIKeyScopeTemplateDelete,
	APIKeyScopeTemplateRead,
	APIKeyScopeTemplateUpdate,
	APIKeyScopeTemplateUse,
	APIKeyScopeUserReadPersonal,
	APIKeyScopeUserUpdatePersonal,
	APIKeyScopeUserSecretAll,
	APIKeyScopeUserSecretCreate,
	APIKeyScopeUserSecretDelete,
	APIKeyScopeUserSecretRead,
	APIKeyScopeUserSecretUpdate,
	APIKeyScopeWorkspaceAll,
	APIKeyScopeWorkspaceApplicationConnect,
	APIKeyScopeWorkspaceCreate,
	APIKeyScopeWorkspaceDelete,
	APIKeyScopeWorkspaceRead,
	APIKeyScopeWorkspaceSsh,
	APIKeyScopeWorkspaceStart,
	APIKeyScopeWorkspaceStop,
	APIKeyScopeWorkspaceUpdate,
}
