package codersdk

var Countries = []Country{
	{Name: "Afghanistan", Flag: "🇦🇫"},
	{Name: "Åland Islands", Flag: "🇦🇽"},
	{Name: "Albania", Flag: "🇦🇱"},
	{Name: "Algeria", Flag: "🇩🇿"},
	{Name: "American Samoa", Flag: "🇦🇸"},
	{Name: "Andorra", Flag: "🇦🇩"},
	{Name: "Angola", Flag: "🇦🇴"},
	{Name: "Anguilla", Flag: "🇦🇮"},
	{Name: "Antarctica", Flag: "🇦🇶"},
	{Name: "Antigua and Barbuda", Flag: "🇦🇬"},
	{Name: "Argentina", Flag: "🇦🇷"},
	{Name: "Armenia", Flag: "🇦🇲"},
	{Name: "Aruba", Flag: "🇦🇼"},
	{Name: "Australia", Flag: "🇦🇺"},
	{Name: "Austria", Flag: "🇦🇹"},
	{Name: "Azerbaijan", Flag: "🇦🇿"},
	{Name: "Bahamas", Flag: "🇧🇸"},
	{Name: "Bahrain", Flag: "🇧🇭"},
	{Name: "Bangladesh", Flag: "🇧🇩"},
	{Name: "Barbados", Flag: "🇧🇧"},
	{Name: "Belarus", Flag: "🇧🇾"},
	{Name: "Belgium", Flag: "🇧🇪"},
	{Name: "Belize", Flag: "🇧🇿"},
	{Name: "Benin", Flag: "🇧🇯"},
	{Name: "Bermuda", Flag: "🇧🇲"},
	{Name: "Bhutan", Flag: "🇧🇹"},
	{Name: "Bolivia, Plurinational State of", Flag: "🇧🇴"},
	{Name: "Bonaire, Sint Eustatius and Saba", Flag: "🇧🇶"},
	{Name: "Bosnia and Herzegovina", Flag: "🇧🇦"},
	{Name: "Botswana", Flag: "🇧🇼"},
	{Name: "Bouvet Island", Flag: "🇧🇻"},
	{Name: "Brazil", Flag: "🇧🇷"},
	{Name: "British Indian Ocean Territory", Flag: "🇮🇴"},
	{Name: "Brunei Darussalam", Flag: "🇧🇳"},
	{Name: "Bulgaria", Flag: "🇧🇬"},
	{Name: "Burkina Faso", Flag: "🇧🇫"},
	{Name: "Burundi", Flag: "🇧🇮"},
	{Name: "Cambodia", Flag: "🇰🇭"},
	{Name: "Cameroon", Flag: "🇨🇲"},
	{Name: "Canada", Flag: "🇨🇦"},
	{Name: "Cape Verde", Flag: "🇨🇻"},
	{Name: "Cayman Islands", Flag: "🇰🇾"},
	{Name: "Central African Republic", Flag: "🇨🇫"},
	{Name: "Chad", Flag: "🇹🇩"},
	{Name: "Chile", Flag: "🇨🇱"},
	{Name: "China", Flag: "🇨🇳"},
	{Name: "Christmas Island", Flag: "🇨🇽"},
	{Name: "Cocos (Keeling) Islands", Flag: "🇨🇨"},
	{Name: "Colombia", Flag: "🇨🇴"},
	{Name: "Comoros", Flag: "🇰🇲"},
	{Name: "Congo", Flag: "🇨🇬"},
	{Name: "Congo, the Democratic Republic of the", Flag: "🇨🇩"},
	{Name: "Cook Islands", Flag: "🇨🇰"},
	{Name: "Costa Rica", Flag: "🇨🇷"},
	{Name: "Côte d'Ivoire", Flag: "🇨🇮"},
	{Name: "Croatia", Flag: "🇭🇷"},
	{Name: "Cuba", Flag: "🇨🇺"},
	{Name: "Curaçao", Flag: "🇨🇼"},
	{Name: "Cyprus", Flag: "🇨🇾"},
	{Name: "Czech Republic", Flag: "🇨🇿"},
	{Name: "Denmark", Flag: "🇩🇰"},
	{Name: "Djibouti", Flag: "🇩🇯"},
	{Name: "Dominica", Flag: "🇩🇲"},
	{Name: "Dominican Republic", Flag: "🇩🇴"},
	{Name: "Ecuador", Flag: "🇪🇨"},
	{Name: "Egypt", Flag: "🇪🇬"},
	{Name: "El Salvador", Flag: "🇸🇻"},
	{Name: "Equatorial Guinea", Flag: "🇬🇶"},
	{Name: "Eritrea", Flag: "🇪🇷"},
	{Name: "Estonia", Flag: "🇪🇪"},
	{Name: "Ethiopia", Flag: "🇪🇹"},
	{Name: "Falkland Islands (Malvinas)", Flag: "🇫🇰"},
	{Name: "Faroe Islands", Flag: "🇫🇴"},
	{Name: "Fiji", Flag: "🇫🇯"},
	{Name: "Finland", Flag: "🇫🇮"},
	{Name: "France", Flag: "🇫🇷"},
	{Name: "French Guiana", Flag: "🇬🇫"},
	{Name: "French Polynesia", Flag: "🇵🇫"},
	{Name: "French Southern Territories", Flag: "🇹🇫"},
	{Name: "Gabon", Flag: "🇬🇦"},
	{Name: "Gambia", Flag: "🇬🇲"},
	{Name: "Georgia", Flag: "🇬🇪"},
	{Name: "Germany", Flag: "🇩🇪"},
	{Name: "Ghana", Flag: "🇬🇭"},
	{Name: "Gibraltar", Flag: "🇬🇮"},
	{Name: "Greece", Flag: "🇬🇷"},
	{Name: "Greenland", Flag: "🇬🇱"},
	{Name: "Grenada", Flag: "🇬🇩"},
	{Name: "Guadeloupe", Flag: "🇬🇵"},
	{Name: "Guam", Flag: "🇬🇺"},
	{Name: "Guatemala", Flag: "🇬🇹"},
	{Name: "Guernsey", Flag: "🇬🇬"},
	{Name: "Guinea", Flag: "🇬🇳"},
	{Name: "Guinea-Bissau", Flag: "🇬🇼"},
	{Name: "Guyana", Flag: "🇬🇾"},
	{Name: "Haiti", Flag: "🇭🇹"},
	{Name: "Heard Island and McDonald Islands", Flag: "🇭🇲"},
	{Name: "Holy See (Vatican City State)", Flag: "🇻🇦"},
	{Name: "Honduras", Flag: "🇭🇳"},
	{Name: "Hong Kong", Flag: "🇭🇰"},
	{Name: "Hungary", Flag: "🇭🇺"},
	{Name: "Iceland", Flag: "🇮🇸"},
	{Name: "India", Flag: "🇮🇳"},
	{Name: "Indonesia", Flag: "🇮🇩"},
	{Name: "Iran, Islamic Republic of", Flag: "🇮🇷"},
	{Name: "Iraq", Flag: "🇮🇶"},
	{Name: "Ireland", Flag: "🇮🇪"},
	{Name: "Isle of Man", Flag: "🇮🇲"},
	{Name: "Israel", Flag: "🇮🇱"},
	{Name: "Italy", Flag: "🇮🇹"},
	{Name: "Jamaica", Flag: "🇯🇲"},
	{Name: "Japan", Flag: "🇯🇵"},
	{Name: "Jersey", Flag: "🇯🇪"},
	{Name: "Jordan", Flag: "🇯🇴"},
	{Name: "Kazakhstan", Flag: "🇰🇿"},
	{Name: "Kenya", Flag: "🇰🇪"},
	{Name: "Kiribati", Flag: "🇰🇮"},
	{Name: "Korea, Democratic People's Republic of", Flag: "🇰🇵"},
	{Name: "Korea, Republic of", Flag: "🇰🇷"},
	{Name: "Kuwait", Flag: "🇰🇼"},
	{Name: "Kyrgyzstan", Flag: "🇰🇬"},
	{Name: "Lao People's Democratic Republic", Flag: "🇱🇦"},
	{Name: "Latvia", Flag: "🇱🇻"},
	{Name: "Lebanon", Flag: "🇱🇧"},
	{Name: "Lesotho", Flag: "🇱🇸"},
	{Name: "Liberia", Flag: "🇱🇷"},
	{Name: "Libya", Flag: "🇱🇾"},
	{Name: "Liechtenstein", Flag: "🇱🇮"},
	{Name: "Lithuania", Flag: "🇱🇹"},
	{Name: "Luxembourg", Flag: "🇱🇺"},
	{Name: "Macao", Flag: "🇲🇴"},
	{Name: "Macedonia, the Former Yugoslav Republic of", Flag: "🇲🇰"},
	{Name: "Madagascar", Flag: "🇲🇬"},
	{Name: "Malawi", Flag: "🇲🇼"},
	{Name: "Malaysia", Flag: "🇲🇾"},
	{Name: "Maldives", Flag: "🇲🇻"},
	{Name: "Mali", Flag: "🇲🇱"},
	{Name: "Malta", Flag: "🇲🇹"},
	{Name: "Marshall Islands", Flag: "🇲🇭"},
	{Name: "Martinique", Flag: "🇲🇶"},
	{Name: "Mauritania", Flag: "🇲🇷"},
	{Name: "Mauritius", Flag: "🇲🇺"},
	{Name: "Mayotte", Flag: "🇾🇹"},
	{Name: "Mexico", Flag: "🇲🇽"},
	{Name: "Micronesia, Federated States of", Flag: "🇫🇲"},
	{Name: "Moldova, Republic of", Flag: "🇲🇩"},
	{Name: "Monaco", Flag: "🇲🇨"},
	{Name: "Mongolia", Flag: "🇲🇳"},
	{Name: "Montenegro", Flag: "🇲🇪"},
	{Name: "Montserrat", Flag: "🇲🇸"},
	{Name: "Morocco", Flag: "🇲🇦"},
	{Name: "Mozambique", Flag: "🇲🇿"},
	{Name: "Myanmar", Flag: "🇲🇲"},
	{Name: "Namibia", Flag: "🇳🇦"},
	{Name: "Nauru", Flag: "🇳🇷"},
	{Name: "Nepal", Flag: "🇳🇵"},
	{Name: "Netherlands", Flag: "🇳🇱"},
	{Name: "New Caledonia", Flag: "🇳🇨"},
	{Name: "New Zealand", Flag: "🇳🇿"},
	{Name: "Nicaragua", Flag: "🇳🇮"},
	{Name: "Niger", Flag: "🇳🇪"},
	{Name: "Nigeria", Flag: "🇳🇬"},
	{Name: "Niue", Flag: "🇳🇺"},
	{Name: "Norfolk Island", Flag: "🇳🇫"},
	{Name: "Northern Mariana Islands", Flag: "🇲🇵"},
	{Name: "Norway", Flag: "🇳🇴"},
	{Name: "Oman", Flag: "🇴🇲"},
	{Name: "Pakistan", Flag: "🇵🇰"},
	{Name: "Palau", Flag: "🇵🇼"},
	{Name: "Palestine, State of", Flag: "🇵🇸"},
	{Name: "Panama", Flag: "🇵🇦"},
	{Name: "Papua New Guinea", Flag: "🇵🇬"},
	{Name: "Paraguay", Flag: "🇵🇾"},
	{Name: "Peru", Flag: "🇵🇪"},
	{Name: "Philippines", Flag: "🇵🇭"},
	{Name: "Pitcairn", Flag: "🇵🇳"},
	{Name: "Poland", Flag: "🇵🇱"},
	{Name: "Portugal", Flag: "🇵🇹"},
	{Name: "Puerto Rico", Flag: "🇵🇷"},
	{Name: "Qatar", Flag: "🇶🇦"},
	{Name: "Réunion", Flag: "🇷🇪"},
	{Name: "Romania", Flag: "🇷🇴"},
	{Name: "Russian Federation", Flag: "🇷🇺"},
	{Name: "Rwanda", Flag: "🇷🇼"},
	{Name: "Saint Barthélemy", Flag: "🇧🇱"},
	{Name: "Saint Helena, Ascension and Tristan da Cunha", Flag: "🇸🇭"},
	{Name: "Saint Kitts and Nevis", Flag: "🇰🇳"},
	{Name: "Saint Lucia", Flag: "🇱🇨"},
	{Name: "Saint Martin (French part)", Flag: "🇲🇫"},
	{Name: "Saint Pierre and Miquelon", Flag: "🇵🇲"},
	{Name: "Saint Vincent and the Grenadines", Flag: "🇻🇨"},
	{Name: "Samoa", Flag: "🇼🇸"},
	{Name: "San Marino", Flag: "🇸🇲"},
	{Name: "Sao Tome and Principe", Flag: "🇸🇹"},
	{Name: "Saudi Arabia", Flag: "🇸🇦"},
	{Name: "Senegal", Flag: "🇸🇳"},
	{Name: "Serbia", Flag: "🇷🇸"},
	{Name: "Seychelles", Flag: "🇸🇨"},
	{Name: "Sierra Leone", Flag: "🇸🇱"},
	{Name: "Singapore", Flag: "🇸🇬"},
	{Name: "Sint Maarten (Dutch part)", Flag: "🇸🇽"},
	{Name: "Slovakia", Flag: "🇸🇰"},
	{Name: "Slovenia", Flag: "🇸🇮"},
	{Name: "Solomon Islands", Flag: "🇸🇧"},
	{Name: "Somalia", Flag: "🇸🇴"},
	{Name: "South Africa", Flag: "🇿🇦"},
	{Name: "South Georgia and the South Sandwich Islands", Flag: "🇬🇸"},
	{Name: "South Sudan", Flag: "🇸🇸"},
	{Name: "Spain", Flag: "🇪🇸"},
	{Name: "Sri Lanka", Flag: "🇱🇰"},
	{Name: "Sudan", Flag: "🇸🇩"},
	{Name: "Suriname", Flag: "🇸🇷"},
	{Name: "Svalbard and Jan Mayen", Flag: "🇸🇯"},
	{Name: "Swaziland", Flag: "🇸🇿"},
	{Name: "Sweden", Flag: "🇸🇪"},
	{Name: "Switzerland", Flag: "🇨🇭"},
	{Name: "Syrian Arab Republic", Flag: "🇸🇾"},
	{Name: "Taiwan, Province of China", Flag: "🇹🇼"},
	{Name: "Tajikistan", Flag: "🇹🇯"},
	{Name: "Tanzania, United Republic of", Flag: "🇹🇿"},
	{Name: "Thailand", Flag: "🇹🇭"},
	{Name: "Timor-Leste", Flag: "🇹🇱"},
	{Name: "Togo", Flag: "🇹🇬"},
	{Name: "Tokelau", Flag: "🇹🇰"},
	{Name: "Tonga", Flag: "🇹🇴"},
	{Name: "Trinidad and Tobago", Flag: "🇹🇹"},
	{Name: "Tunisia", Flag: "🇹🇳"},
	{Name: "Turkey", Flag: "🇹🇷"},
	{Name: "Turkmenistan", Flag: "🇹🇲"},
	{Name: "Turks and Caicos Islands", Flag: "🇹🇨"},
	{Name: "Tuvalu", Flag: "🇹🇻"},
	{Name: "Uganda", Flag: "🇺🇬"},
	{Name: "Ukraine", Flag: "🇺🇦"},
	{Name: "United Arab Emirates", Flag: "🇦🇪"},
	{Name: "United Kingdom", Flag: "🇬🇧"},
	{Name: "United States", Flag: "🇺🇸"},
	{Name: "United States Minor Outlying Islands", Flag: "🇺🇲"},
	{Name: "Uruguay", Flag: "🇺🇾"},
	{Name: "Uzbekistan", Flag: "🇺🇿"},
	{Name: "Vanuatu", Flag: "🇻🇺"},
	{Name: "Venezuela, Bolivarian Republic of", Flag: "🇻🇪"},
	{Name: "Vietnam", Flag: "🇻🇳"},
	{Name: "Virgin Islands, British", Flag: "🇻🇬"},
	{Name: "Virgin Islands, U.S.", Flag: "🇻🇮"},
	{Name: "Wallis and Futuna", Flag: "🇼🇫"},
	{Name: "Western Sahara", Flag: "🇪🇭"},
	{Name: "Yemen", Flag: "🇾🇪"},
	{Name: "Zambia", Flag: "🇿🇲"},
	{Name: "Zimbabwe", Flag: "🇿🇼"},
}

// @typescript-ignore Country
type Country struct {
	Name string `json:"name"`
	Flag string `json:"flag"`
}
