# This is the base image used for Coder images. It's a multi-arch image that is
# built in depot.dev for all supported architectures. Since it's built on real
# hardware and not cross-compiled, it can have "RUN" commands.
FROM alpine:3.18.2

# We use a single RUN command to reduce the number of layers in the image.
# NOTE: Keep the Terraform version in sync with minTerraformVersion and
# maxTerraformVersion in provisioner/terraform/install.go.
RUN apk add --no-cache \
		curl \
		wget \
		bash \
		jq \
		git \
		# Fixes CVE-2023-3446 and CVE-2023-2975. Only necessary until Alpine 3.18.3.
		openssl \
		openssh-client && \
	# Use the edge repo, since Terraform doesn't seem to be backported to 3.18.
	apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
		terraform=~1.5 && \
	addgroup \
		-g 1000 \
		coder && \
	adduser \
		-D \
		-s /bin/bash \
		-h /home/coder \
		-u 1000 \
		-G coder \
		coder

USER 1000:1000
ENV HOME=/home/coder
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt
WORKDIR /home/coder
