FROM debian:bookworm-slim@sha256:3783cc01769c7b2b1b83a5c5ad96c815348e28ed7da68e2e3687004faa906251
RUN apt-get update && apt-get install -y --no-install-recommends python3 ca-certificates && rm -rf /var/lib/apt/lists/*
COPY executor-entrypoint.py /usr/local/bin/executor-entrypoint.py
ENTRYPOINT ["python3", "/usr/local/bin/executor-entrypoint.py"]
