{
 "title": "Coder Scaletest Dashboard",
 "time": { "from": "2023-06-27T11:56:59.659Z", "to": "2023-06-27T16:04:43.640Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(coderd_api_concurrent_requests,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(coderd_api_concurrent_requests,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(coderd_api_concurrent_requests,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Control Plane Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coder CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"}[$__rate_interval])) ",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Coder memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Coder Network TX/RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (-rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"^(coder|provisionerd)-[^-]+-[^-]+$\"}[$__rate_interval]))",
     "legendFormat": "tx {{pod}}"
    },
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"^(coder|provisionerd)-[^-]+-[^-]+$\"}[$__rate_interval]))",
     "legendFormat": "rx {{pod}"
    }
   ]
  },
  {
   "title": "Coder pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (delta(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "DB insert/update/delete/return",
   "type": "timeseries",
   "description": "LOGARITHMIC Y AXIS",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "INSERT"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "RETURN"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "FETCH"
    }
   ]
  },
  {
   "title": "DB conns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"${cluster}-coder\", cluster=~\"${cluster}\", state=\"active\"} !=0",
     "legendFormat": "active"
    },
    {
     "expr": "pg_stat_activity_count{datname=~\"${cluster}-coder\", cluster=~\"${cluster}\", state=\"idle\"} !=0",
     "legendFormat": "idle"
    },
    {
     "expr": "pg_stat_activity_count{datname=~\"${cluster}-coder\", cluster=~\"${cluster}\", state=\"idle in transaction\"} != 0",
     "legendFormat": "idle_tx"
    },
    {
     "expr": "pg_stat_activity_count{datname=~\"${cluster}-coder\", cluster=~\"${cluster}\", state=\"disabled\"} != 0",
     "legendFormat": "disabled"
    }
   ]
  },
  {
   "title": "DB TX/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "sqlQuerier P95 execution timing",
   "type": "heatmap",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, query) (rate(coderd_db_query_latencies_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sqlQuerier execution count",
   "type": "heatmap",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(le, query) (rate(coderd_db_query_latencies_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(rate(coderd_api_requests_processed_total{cluster=\"$cluster\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(coderd_api_requests_processed_total{cluster=\"$cluster\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "API requests/sec by response, method",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by (code,method) (rate(coderd_api_requests_processed_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=\"coder\",code!=\"0\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "API Request Latency P95",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(coderd_api_request_latencies_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", path=~\"^/api/v2/.*\"}[$__rate_interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, path) (rate(coderd_api_request_latencies_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", path=~\"^/api/v2/.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "Workspace Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Scaletest Workspace CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"coder-scaletest-.*-scaletest-.*\", resource=\"cpu\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"coder-scaletest-.*-scaletest-.*\", container=\"dev\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaletest Workspace Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{cluster=~\"${cluster}\", namespace=~\"${namespace}\", pod=~\"coder-scaletest-.*-scaletest-.*\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"${cluster}\", namespace=~\"${namespace}\", pod=~\"coder-scaletest-.*-scaletest-.*\"}[$__rate_interval])) * -1",
     "legendFormat": "tx {{pod}}"
    }
   ]
  },
  {
   "title": "Scaletest Workspace Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"coder-scaletest-.*-scaletest-.*\", resource=\"memory\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"coder-scaletest-.*-scaletest-.*\", container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workspace Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Agent Connection RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(coderd_agentstats_rx_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(coderd_agentstats_tx_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) * -1",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Agent Connection Latency P50/95/99",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, coderd_agents_connection_latencies_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.95, coderd_agents_connection_latencies_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.99, coderd_agents_connection_latencies_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Websocket Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(coderd_api_concurrent_websockets{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"coder\"})",
     "legendFormat": "Websockets"
    }
   ]
  },
  {
   "title": "Agent Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(coderd_agents_connections{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workspace Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Workspace Traffic bytes TX/RX",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(coderd_scaletest_bytes_written_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=\"coder-scaletest-workspace-traffic\"}[$__rate_interval])) * -1",
     "legendFormat": "tx inside container"
    },
    {
     "expr": "sum by(pod) (rate(coderd_scaletest_bytes_read_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=\"coder-scaletest-workspace-traffic\"}[$__rate_interval]))",
     "legendFormat": "rx inside container"
    },
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=\"coder-scaletest-workspace-traffic\"}[$__rate_interval])) * 1",
     "legendFormat": "rx outside container"
    },
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=\"coder-scaletest-workspace-traffic\"}[$__rate_interval])) * -1",
     "legendFormat": "tx outside container"
    }
   ]
  },
  {
   "title": "Workspace Traffic read latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(coderd_scaletest_read_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace Traffic write latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(coderd_scaletest_write_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace Traffic Read errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "sum(rate(coderd_scaletest_read_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace Traffic Write errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "sum(rate(coderd_scaletest_write_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Generation CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=\"coder-scaletest-workspace-traffic\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Generation Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=\"coder-scaletest-workspace-traffic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic generation pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=\"coder-scaletest-workspace-traffic\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "AuthZ Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(coderd_authz_authorize_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(coderd_authz_authorize_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(coderd_authz_authorize_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Provisioner Job Timings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(coderd_provisionerd_job_timings_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p50-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, pod) (rate(coderd_provisionerd_job_timings_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p90-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(coderd_provisionerd_job_timings_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p95-{{pod}}"
    }
   ]
  },
  {
   "title": "Total Workspace Builds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "targets": [
    {
     "expr": "sum by(status, pod) (coderd_workspace_builds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workspace_transition=\"START\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent Provisioner Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "targets": [
    {
     "expr": "sum by(status, container) (coderd_provisionerd_jobs_current{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status, container) (coderd_provisionerd_num_daemons{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "daemons"
    }
   ]
  }
 ]
}