{
 "title": "Bridge Load Testing Metrics",
 "time": { "from": "2025-12-11T18:09:40.000Z", "to": "2025-12-11T18:15:04.000Z" },
 "panels": [
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "process_cpu_seconds_total",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.\n\n**Type:** *counter*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))",
       "legendFormat": "sum(rate)"
      }
     ]
    },
    {
     "title": "process_resident_memory_bytes",
     "type": "timeseries",
     "description": "Resident memory size in bytes.\n\n**Type:** *gauge*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(process_resident_memory_bytes{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "process_network_transmit_bytes_total",
     "type": "timeseries",
     "description": "Number of bytes transmitted by the process over the network.\n\n**Type:** *counter*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(process_network_transmit_bytes_total{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))",
       "legendFormat": "sum(rate)"
      }
     ]
    },
    {
     "title": "process_network_receive_bytes_total",
     "type": "timeseries",
     "description": "Number of bytes received by the process over the network.\n\n**Type:** *counter*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(process_network_receive_bytes_total{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))",
       "legendFormat": "sum(rate)"
      }
     ]
    },
    {
     "title": "process_open_fds",
     "type": "timeseries",
     "description": "Number of open file descriptors.\n\n**Type:** *gauge*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(process_open_fds{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "go_sql_idle_connections",
     "type": "timeseries",
     "description": "The number of idle connections.\n\n**Type:** *gauge*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(go_sql_idle_connections{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "go_sql_in_use_connections",
     "type": "timeseries",
     "description": "The number of connections currently in use.\n\n**Type:** *gauge*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(go_sql_in_use_connections{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "go_sql_wait_duration_seconds_total",
     "type": "timeseries",
     "description": "The total time blocked waiting for a new connection.\n\n**Type:** *counter*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(go_sql_wait_duration_seconds_total{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))",
       "legendFormat": "sum(rate)"
      }
     ]
    },
    {
     "title": "coderd_db_tx_duration_seconds_bucket",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(coderd_db_tx_duration_seconds_bucket{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "go_memstats_heap_alloc_bytes",
     "type": "timeseries",
     "description": "Number of heap bytes allocated and currently in use, same as go_memstats_alloc_bytes. Equals to /memory/classes/heap/objects:bytes.\n\n**Type:** *gauge*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(go_memstats_heap_alloc_bytes{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "go_memstats_heap_inuse_bytes",
     "type": "timeseries",
     "description": "Number of heap bytes that are in use. Equals to /memory/classes/heap/objects:bytes + /memory/classes/heap/unused:bytes\n\n**Type:** *gauge*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "go_memstats_heap_idle_bytes",
     "type": "timeseries",
     "description": "Number of heap bytes waiting to be used. Equals to /memory/classes/heap/released:bytes + /memory/classes/heap/free:bytes.\n\n**Type:** *gauge*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(go_memstats_heap_idle_bytes{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "go_gc_duration_seconds_count",
     "type": "timeseries",
     "description": "Count of events that have been observed for the base metric (A summary of the wall-time pause (stop-the-world) duration in garbage collection cycles.)\n\n**Type:** *counter*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_count{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))",
       "legendFormat": "sum(rate)"
      }
     ]
    },
    {
     "title": "go_gc_duration_seconds",
     "type": "timeseries",
     "description": "A summary of the wall-time pause (stop-the-world) duration in garbage collection cycles.\n\n**Type:** *summary*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "go_gc_duration_seconds_sum",
     "type": "timeseries",
     "description": "Total sum of all observed values for the base metric (A summary of the wall-time pause (stop-the-world) duration in garbage collection cycles.)\n\n**Type:** *counter*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))",
       "legendFormat": "sum(rate)"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "coderd_api_concurrent_requests",
     "type": "timeseries",
     "description": "The number of concurrent API requests.\n\n**Type:** *gauge*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(coderd_api_concurrent_requests{__ignore_usage__=\"\", service=\"coderd\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "coderd_api_request_latencies_seconds_bucket",
     "type": "heatmap",
     "description": "Cumulative counters for the observation buckets (Latency distribution of requests in seconds.)\n\n**Type:** *counter*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(coderd_api_request_latencies_seconds_bucket{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "coderd_api_requests_processed_total",
     "type": "timeseries",
     "description": "The total number of processed API requests\n\n**Type:** *counter*\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(coderd_api_requests_processed_total{__ignore_usage__=\"\", service=\"coderd\"}[$__rate_interval]))",
       "legendFormat": "sum(rate)"
      }
     ]
    }
   ]
  },
  {
   "title": "PubSub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "coder_pubsub_receive_latency_seconds",
   "type": "timeseries",
   "description": "The time taken to receive a message from a pubsub event channel\n\n**Type:** *gauge*\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(coder_pubsub_receive_latency_seconds{__ignore_usage__=\"\", service=\"coderd\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "coder_pubsub_send_latency_seconds",
   "type": "timeseries",
   "description": "The time taken to send a message into a pubsub event channel\n\n**Type:** *gauge*\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(coder_pubsub_send_latency_seconds{__ignore_usage__=\"\", service=\"coderd\"})",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}