// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coder/coder/v2/tailnet (interfaces: Coordinatee)
//
// Generated by this command:
//
//	mockgen -destination ./coordinateemock.go -package tailnettest github.com/coder/coder/v2/tailnet Coordinatee
//

// Package tailnettest is a generated GoMock package.
package tailnettest

import (
	reflect "reflect"

	tailnet "github.com/coder/coder/v2/tailnet"
	proto "github.com/coder/coder/v2/tailnet/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockCoordinatee is a mock of Coordinatee interface.
type MockCoordinatee struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinateeMockRecorder
}

// MockCoordinateeMockRecorder is the mock recorder for MockCoordinatee.
type MockCoordinateeMockRecorder struct {
	mock *MockCoordinatee
}

// NewMockCoordinatee creates a new mock instance.
func NewMockCoordinatee(ctrl *gomock.Controller) *MockCoordinatee {
	mock := &MockCoordinatee{ctrl: ctrl}
	mock.recorder = &MockCoordinateeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinatee) EXPECT() *MockCoordinateeMockRecorder {
	return m.recorder
}

// SetAllPeersLost mocks base method.
func (m *MockCoordinatee) SetAllPeersLost() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAllPeersLost")
}

// SetAllPeersLost indicates an expected call of SetAllPeersLost.
func (mr *MockCoordinateeMockRecorder) SetAllPeersLost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAllPeersLost", reflect.TypeOf((*MockCoordinatee)(nil).SetAllPeersLost))
}

// SetNodeCallback mocks base method.
func (m *MockCoordinatee) SetNodeCallback(arg0 func(*tailnet.Node)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNodeCallback", arg0)
}

// SetNodeCallback indicates an expected call of SetNodeCallback.
func (mr *MockCoordinateeMockRecorder) SetNodeCallback(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNodeCallback", reflect.TypeOf((*MockCoordinatee)(nil).SetNodeCallback), arg0)
}

// UpdatePeers mocks base method.
func (m *MockCoordinatee) UpdatePeers(arg0 []*proto.CoordinateResponse_PeerUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePeers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePeers indicates an expected call of UpdatePeers.
func (mr *MockCoordinateeMockRecorder) UpdatePeers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePeers", reflect.TypeOf((*MockCoordinatee)(nil).UpdatePeers), arg0)
}
